### ISSUE TITLE
Material theme for slider and range slider

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1001]
Material slider info can be found here: https://material.io/develop/web/components/input-controls/sliders/

I believe there is a `@material` package that provides classes for composition. We may need to make changes to our existing widget implementation to support this.

**Comment by JamesLMilner** [comment]
The way that the `Slider` widget is is currently composed doesn't align with the material stylings. For example the thumb is an SVG and not a `<span>`. It might be worth rethinking the composition of the slider widget, or trying a different approach.
