### ISSUE TITLE
Remove box sizing: border-box styles

### ISSUE THREAD

**Issue by samends** [dojo/widgets#1009]
**Enhancement** 

Currently many widget styles contain the styling `box-sizing: border-box` however as border-box is the standard default for all major browsers we are supporting, these styles are no longer needed.

Package Version: 7.0.0-pre

**Comment by tomdye** [comment]
The default box-sizing model is actually `content-box`, so our use of `box-sizing: border-box` is appropriate for laying out our nodes. I think that the initial concern here was related to having `.root * { }` selectors which were setting the box-sizing model blindly on all child nodes which was incorrect. It appears that these were already fixed when we addressed the css-warnings we were seeing in our build process.
