### ISSUE TITLE
API Doc Review for widgets

### ISSUE THREAD

**Issue by eheasley** [dojo/widgets#101]
Review the generated API documentation for `widgets` at http://dojo.io/api/. If any of the information is not accurate, please make the necessary adjustments to the API documentation within this repo.

**Comment by rishson** [comment]
We are pulling in `/tests` - things such as `App, TunnelOptions` - we should exclude.

**Comment by rishson** [comment]
Have also raised #106 due to inconsistent naming conventions.

**Comment by bitpshr** [comment]
- Property interfaces should probably be listed on each component page

**Comment by eheasley** [comment]
We confirmed today that this has been cleaned up generally across the board.  If any specific issues are noted going forward we can open new issues to address those at that time.
