### ISSUE TITLE
adopt use of theme.compose instead of using classes where possible

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1038]
**Enhancement** 

There are several instances where we are using `classes` to pass styles down to child components within our widgets.
We should look into using `theme.compose` with a prefix in these cases in order to allow child widgets to be targeted via a prefix classname. ie. `loginButtonRoot` to target the `root` class of the login button.
This is a better approach than via classes as it will work with our themes.

**Comment by pottedmeat** [comment]
I've tried to outline the nuances of `theme.compose` [here](https://github.com/dojo/widgets/issues/1139). There are a few situations we would need to watch out for:

* Its use would have to be limited only to what's passed in via the `classes` property—making modifications to the widget's existing styles still needs to be done through the embedded widget's `classes` property.
* We would have to be careful that no rules in the widget's CSS share the prefix/rule combination with the embedded widget—doing so would completely override the embedded widget's style for that class.

**Comment by tomdye** [comment]
Essentially the idea of this ticket is to replace instances where we are internally using `classes` to pas styles to child widgets to use `theme.compose` instead. In these instances, the passed in `classes` can still be used as well.
This kind of thing https://github.com/dojo/widgets/blob/master/src/accordion-pane/index.tsx#L77.
However, having just looked in widgets. When looking for these instances please check there is not an open PR to convert to functional open already that has fixed this.

**Comment by tomdye** [comment]
Completed via PRs referenced
