### ISSUE TITLE
Leading / Trailing input sections not working with material theme

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1043]
**Bug** 

leading / trailing sections of text-input do not appear when using the material theme.

**Comment by ericos** [comment]
This looks to be working now. https://widgets.dojo.io/#widget/text-input/example/leadingtrailing

![Screen Shot 2020-02-14 at 9 24 47 AM](https://user-images.githubusercontent.com/1054198/74543960-f14fe100-4f0b-11ea-8b43-60f39b75d7d9.png)

**Comment by tomdye** [comment]
This appears to be working to closing
