### ISSUE TITLE
Material theme for DateInput widget

### ISSUE THREAD

**Issue by jellison** [dojo/widgets#1073]
## Overview

Create a compatible Material theme for the DateInput widget.

MDC Design: https://material.io/components/pickers/#desktop-pickers

![image](https://user-images.githubusercontent.com/41762295/73656623-87f3e680-465e-11ea-8e25-16de5b0b6971.png)

**Comment by jellison** [comment]
@tomdye Should we follow the Material design spec or model after the (Angular Material)[https://material.angular.io/components/datepicker/overview] implementation?

Specifically, the Material spec 1) shows no icon, just a text input; 2) upon selection allows interaction with both the text input and the calendar.

If we follow the Material spec, we need to reconcile the `popup` functionality and allowing access to only the input (which would be outside the popup content).

**Comment by tomdye** [comment]
I think that for now we should maintain the current interaction and just go with material styles only.
With regards to the icon, I think it's fine to keep is as we're using it as a trigger to open the modal, we just need to ensure that the icon is clickable. We should also ensure that the leading / trailing icons on our text inputs are the correct colour etc.

**Comment by jellison** [comment]
I agree. I think the linked PR will suffice then. https://github.com/dojo/widgets/pull/1079
