### ISSUE TITLE
Tidy up and remove unused parts of widget

### ISSUE THREAD

**Issue by Tomdye** [dojo/widgets#111]
**Enhancement**

The addition of `widgetBase` and the `d` utils has changed our widget direction sufficiently that a lot of the other mixins and files are no longer required.

To avoid confusion and people contributing to the deprecated parts of the widget code base we should begin work on removing deprecated parts of this package.

**Comment by matt-gadd** [comment]
We can also remove the following I believe:
`bower.json` - we currently don't publish to
`src/interfaces.ts` - only contains the loader which now lives in `dojo-interfaces`
`src/util/query.ts` - not used anywhere as far as I can see
`src/util/lang.ts` - should be dispersed to whatever uses it - some part of it are no longer needed, some parts are completely untested
`src/themes/structural/common.js` - not structural
`examples` - will shortly be broken anyway

**Comment by Tomdye** [comment]
Also removing the postCSS and structural styles for the time being, they will be re-introduced under the re-structure issue / pr
