### ISSUE TITLE
Pagination widget

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1123]
TBD

**Comment by jellison** [comment]
Some features to consider...

####  Must-have
- Next/Prev
- +/- `x` pages
![image](https://user-images.githubusercontent.com/41762295/76764818-e044fa80-676b-11ea-8865-3d252d440de2.png)

#### Optional
- Next/Prev labels
![image](https://user-images.githubusercontent.com/41762295/76764542-657bdf80-676b-11ea-9851-d995dd88ed51.png)
- Next `x` pages
![image](https://user-images.githubusercontent.com/41762295/76764908-010d5000-676c-11ea-9085-f2e4baec909f.png)
- Manual page input
- Page size selector
- Summary
![image](https://user-images.githubusercontent.com/41762295/76763774-239e6980-676a-11ea-8a23-2119e5f28e4b.png)

Some thoughts on what the basic API would look like:
- `page` - current page number
- `total` - total number of available pages
- `onPageChange(newPage)` - callback for when page changes

Page size API:
- `pageSize` - number of items per page
- `pageSizes` - options for page size selection
- `onPageSizeChange(newPageSize)` - callback for when page size changes

**Comment by jellison** [comment]
I guess we're going "uncontrolled" these days heh? So `page` should really be `initialPage` right?

**Comment by tomdye** [comment]
I think that this would be a controlled widget as it would simply tell another widget to change page etc and need to display the current page incase the page number etc changes via another source, so no `initialPage`

**Comment by tomdye** [comment]
Good start @jellison, not 100% on the `pageSizes` property though, what would that look like?

**Comment by jellison** [comment]
Not sure entirely. Thought it would be a way to allow customizing the page size selector:

![image](https://user-images.githubusercontent.com/41762295/76785866-8d2f6f80-678c-11ea-9697-8439f6963a96.png)

It could be `Array<{ label: string, pageSize: number}>` (probably put that into a type though). Too much?

**Comment by tomdye** [comment]
I think `pageSizes` should be `MenuOption[]` which supports `{label: string; value: number;}` IIRC

**Comment by jellison** [comment]
> I think `pageSizes` should be `MenuOption[]` which supports `{label: string; value: number;}` IIRC

With the latest changes to Menu/List, do you still think some reuse of `ListOption` is warranted?

`export type ListOption = { value: string; label?: string; disabled?: boolean; divider?: boolean };`
