### ISSUE TITLE
Star rating widget

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1127]
Please put design / thoughts on this ticket.
We should create a star rating widget drawing inspiration from:

- https://ant.design/components/rate/
- https://material-ui.com/components/rating/

We should keep the design as simple as possible. The widget should be uncontrolled.

**Comment by pottedmeat** [comment]
I'm looking into the possibility of using `RadioGroup` as a base widget—the recommended WAI approach is to use a hidden labeled radio group (with a 0 value).

We do not currently have a star `Icon` but this seems like it should be the approach we should use, especially for future functionality of partial ratings.

**Basic Functionality**:

* Whole-number stars from 0 to `max`
* An initial value
* An `onValue` notification
* The radio group `name`

```typescript
interface RateProperties {
	initialValue?: number; 
	onValue?: (value: number): void;
	max?: number; 
	name?: string;
}
```

```typescript
interface RateChildren {
	(fill: number, index: number): RenderResult;
}
```

```html
<Rate>
	{(fill, index) => (
		<span styles={{color: fill ? 'green' : 'red'}}>{index > 3 ? '👍' : '👎'}</span>
	)
</Rate>
```

**Future Functionality**:

* Clear when clicking on the existing rating (`allowClear?: boolean;`)
* Partial rating (`precision?: number;`)
* Hover value notification (`onHoverValue?: (value: number): void;`)
* Disabled/readonly states
* Configurable a11y labels ("0 Stars", "1 Star", "2 Stars"... will be used by default)
	* If this should be done through a child render function, I think I should plan for this now and tuck the renderer under a render function
* Expose labels as `helpText` to show either current or hovered values
* Set value from keyboard when hovering

**Comment by tomdye** [comment]
Looks good to me, couple of thoughts:
- We should support disabled straight away
- Can we use our existing radiogroup widget with a custom renderer?
- `fill` param to the custom renderer should be a boolean and probably be `selected` / `toggled` / `active` perhaps to denote it's state rather than it's appearance.
- This should be keyboard accessibly and allow key presses to move focus / select choice

**Comment by pottedmeat** [comment]
* 👍
* I'll see how I can work around RadioGroup/Radio. One consideration that will need to be made is for `label` to be a `DNode`
* `fill` would allow both boolean `if` checks and partial fills. The state discussion is interesting—`selected` seems important and it makes me think that `hover` state is important. There is a third state that I'm not sure about which would be only relevant during hover and would be what the mouse is currently over.
* 👍

**Comment by pottedmeat** [comment]
@scott-jensen or @itorrey looking for what colors we would use. For selected stars, Ant uses #fadb14 and Material uses #ffb400. For the empty stars I'm currently using the default icon fill. For disabled, I'm setting the opacity to 50%.

**Comment by agubler** [comment]
This has been completed https://github.com/dojo/widgets/pull/1460
