### ISSUE TITLE
Convention for internal-use properties?

### ISSUE THREAD

**Issue by mwistrand** [dojo/widgets#113]
**Enhancement**

When authoring a group of widgets that is intended to be used together (e.g., list + list item), the parent widget may need to manually iterate over its children to set specific properties that developers should avoid setting themselves. For example, the `Menu` widget (currently under development) needs the ability to control which menu item should be highlighted for keyboard navigation upon opening, and thus passes in an `activeIndex` property that is really intended for internal use only.

It would be nice if there were a standard means of marking such properties as internal-use so that developers using these widgets can know at a glance that they should avoid using those properties. Since `widget-core` is already using the `__propertyOrMethodName__` convention, perhaps that could be adopted here as well?

**Comment by agubler** [comment]
As all properties need to be passed to a widget, they fundamentally cannot be "internal" or "private". If something is not intended to be public then it would need to be controlled internally, as soon as it is exposed as property then it is a valid property for any consumer to use.

**Comment by mwistrand** [comment]
Could not the same argument be made for `__render__` or `__setProperties__`? They are public and therefore "valid [methods] for any consumer to use". Properties are really the only interface between widgets, so as soon as it makes sense to split functionality into parent-child widgets, using properties is the only option a widget author has.

As noted in the issue description, the motivation for this is programmatically determining whether a menu item can receive focus. By default, all menu items except the first in a menu have `tabIndex: -1`, until the user tabs out of a menu after navigating within it, in which case that menu item should not have focus, but should have `tabIndex: 0`. Consumers can control this themselves, but should be very cautious about doing so. Since the parent `Menu` has no access to the `MenuItem`'s DOM node, is it even possible to handle this without going through properties?

**Comment by agubler** [comment]
I don't think that they are quite the same paradigm; They are public due to the necessity to call them in the widget core system but effectively they are supposed private to consumers (and form the basis of one of the key principles of the widget system). Which I think is different to "use this property with caution".

However don't understand why we need to expose `activeIndex` via the `Menu`s properties? Couldn't that be managed internally by the `Menu`? What is the use case for exposing the `activeIndex` property outside of the `Menu`? And if there is a use case then I think it's actually a valid property.

**Comment by kitsonk** [comment]
Can we action this and decide what our pattern is?

My opinion is there really isn't something as a _private_ property.  Even if they are designed to work together, they should be designed to be separable.  If they aren't separable, then they are not different classes of widgets and the properties make up the public API of the widget.  Widgets should not be passing hidden state between instances.  If it affects the widget, then any external actor should be able to interface with that property.

If there needs to be state communication between peers of widgets, that should be done through an outer controlling widget, which coordinates the appropriate properties between the two widgets and exposes a reduced public properties API.

**Comment by agubler** [comment]
I share a similar opinion, I think that we could close this issue.
