### ISSUE TITLE
`createWidgetBase` should automatically mixin `VNodeEvented`

### ISSUE THREAD

**Issue by agubler** [dojo/widgets#115]
**Enhancement** 

Mixin `VNodeEvented` to the base widget so that it is available for all consumers.

Package Version: latest

**Comment by kitsonk** [comment]
Or would it just make sense to incorporate that...  Does maintaining it as a separate mixin make sense?  I know we exploded things out bit if a base is going to have it in, I don't know if there is a significant advantage to keep it as a separate mixin.

**Comment by agubler** [comment]
@kitsonk separation of concerns perhaps for maintainability and testability.
