### ISSUE TITLE
Common Select/dropdown base widget

### ISSUE THREAD

**Issue by smhigley** [dojo/widgets#117]
**Enhancement**

The dropdowns in Select, ComboBox, and TimePicker are similar enough that I think we should discuss using a common base for all three, possibly by splitting Select into three separate widgets and using custom Select as a generic dropdown-selection widget.

Benefits:
- Standardized keyboard interaction, controlled and updated in one place (e.g. adding home/end keys would be easy)
- Standard approach to focusing (either moving the focus directly on the options or using `aria-activedescendant`)
- Styling and theming is in one place
- Easier to add features like position detection for rendering the menu above or below the menu trigger

**Comment by dylans** [comment]
I certainly like not having multiple implementations of almost the same thing, and dealing with the inconsistency that introduces (see Dijit's ComboBox, Select, and FilteringSelect for this problem in action).

**Comment by sebilasse** [comment]
👍 
this is just a cc. for https://github.com/Semantic-Org/Semantic-UI/issues/5420 because it's Dropdown could inherit from this base class.
