### ISSUE TITLE
theme.compose can create empty keys

### ISSUE THREAD

**Issue by pottedmeat** [dojo/widgets#1206]
**Bug** 

When a CSS key matches the prefix exactly, it becomes an empty string.

**Expected behavior:**

The key should be left as-is.

**Actual behavior:**

The key becomes an empty string.

**Comment by agubler** [comment]
@pottedmeat can you please provide an example to demonstrate the issue?

**Comment by pottedmeat** [comment]
Added as a test to widget's theme middleware.

I ran into it in an issue where there was a class `.input` used in the parent widget and then the prefix `'input'` used on the embedded widget.
