### ISSUE TITLE
Pass 'stateFrom` to child node renderers

### ISSUE THREAD

**Issue by agubler** [dojo/widgets#121]
**Enhancement** 

To enable `d` to manage widgets where state is managed out side of the parents entry in the widget store, it would be useful to add a handle to `stateFrom` attribute so that an `id` and `stateFrom` can be passed when using `d`.

Package Version: Latest

**Comment by kitsonk** [comment]
I am trying to understand the specific use case this would solve.  What problem does it fix?  Why are we leaking information about the parent that no sub widget be aware of?  The instance is already the `this` to renderer, so `this.id` should be all that is ever depended upon, or `this.state`... where that is stored is not a concern of a sub widget.

**Comment by agubler** [comment]
This would allow a composite widget to include a widget as a child that has it's state stored in the widget store and not part of the parents state.

**Comment by kitsonk** [comment]
As discussed, we are going to expose this as `stateful.stateFrom` and the child node renderer will just use the context of `this` if it needs to access this.

**Comment by agubler** [comment]
Resolved by https://github.com/dojo/compose/issues/105
