### ISSUE TITLE
Calendar: Use theme.compose with child widgets

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1219]
Calendar should use `theme.compose` when creating child widgets. This will enable users to theme the calendar and it's components more easily.

**Comment by maier49** [comment]
All the other examples of using `theme.compose` I've seen are when the child widget has its own css file. For the calendar both `DatePicker` and `CalendarCell` use the calendar's theme css file. Should that be split out, or does it make sense to `compose(calendarCss, css)`?
