### ISSUE TITLE
Date Input theme is not working

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1235]
**Bug** 

Data-input appears unthemed. This may simply need to compose from elsewhere or there may be a larger underlying issue.

<img width="184" alt="Screenshot 2020-03-31 20 10 24" src="https://user-images.githubusercontent.com/814453/78065782-ad198280-738b-11ea-8226-6011efad069e.png">

**Comment by jellison** [comment]
Theme issues resolved in #1322. What's remaining is a Parade/Framework issue.
