### ISSUE TITLE
Update classnames and widget structure to be consistent

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#124]
**Enhancement** 
Iron out differences between widgets. Common classnames should be used for drop downs, options, triggers etc...
Inner-structure of form components should be consistent and predictable.

**Comment by bitpshr** [comment]
We should be able to close this issue now. All components now use more consistently-named CSS classes for common elements. This work was done over several PRs including each individual theme PR and @smhigley's ListBox PR.
