### ISSUE TITLE
Dialog theme is not working

### ISSUE THREAD

**Issue by jellison** [dojo/widgets#1312]
#### Bug

Dialog appears mostly unthemed. Likely due to a theme compose prefix without a composes in the dojo theme to re-apply the original styles as well as the changes.

### Actual

![image](https://user-images.githubusercontent.com/41762295/78372955-ea526000-7597-11ea-9c73-666a2f8873a7.png)

### Expected

![image](https://user-images.githubusercontent.com/41762295/78373013-00f8b700-7598-11ea-83d4-f1965d9df9df.png)

![image](https://user-images.githubusercontent.com/41762295/78373118-271e5700-7598-11ea-8fd9-dcbce3718c82.png)

**Comment by tomdye** [comment]
This issue is related to a fix required to parade. We can close this issue.
