### ISSUE TITLE
RaisedButton theme not working

### ISSUE THREAD

**Issue by jellison** [dojo/widgets#1314]
#### Bug

RaisedButton theme isn't working correctly. Likely due to a theme compose prefix without a composes in the dojo theme to re-apply the original styles as well as the changes.

### Actual

![image](https://user-images.githubusercontent.com/41762295/78373518-b3c91500-7598-11ea-96d2-cbb2b3bfd7e8.png)

### Expected

![image](https://user-images.githubusercontent.com/41762295/78373553-c04d6d80-7598-11ea-9c99-51f7bb290b94.png)

**Comment by tomdye** [comment]
This issue is related to a fix required to parade. We can close this issue.
