### ISSUE TITLE
Select theme not working

### ISSUE THREAD

**Issue by jellison** [dojo/widgets#1315]
#### Bug

Select theme isn't working correctly. Likely due to a theme compose prefix without a composes in the dojo theme to re-apply the original styles as well as the changes.

### Actual

![image](https://user-images.githubusercontent.com/41762295/78373676-e8d56780-7598-11ea-9b60-4cc7615e21cc.png)

### Expected

![image](https://user-images.githubusercontent.com/41762295/78373726-f854b080-7598-11ea-9cbf-972013a603ad.png)

**Comment by tomdye** [comment]
This issue is related to a fix required to parade. We can close this issue.
