### ISSUE TITLE
TimePicker theme not working

### ISSUE THREAD

**Issue by jellison** [dojo/widgets#1318]
#### Bug

TimePicker theme isn't working correctly. Likely due to a theme compose prefix without a composes in the dojo theme to re-apply the original styles as well as the changes.

### Actual

![image](https://user-images.githubusercontent.com/41762295/78374123-7749e900-7599-11ea-86cb-47c9411bed2d.png)

### Expected

![image](https://user-images.githubusercontent.com/41762295/78374171-83ce4180-7599-11ea-9c7b-5e7a2e54fe6e.png)

**Comment by tomdye** [comment]
This issue is related to a fix required to parade. We can close this issue.
