### ISSUE TITLE
Controlled properties for widgets

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1330]
# Controlled properties

## The Problem

A need has arisen to fully control the `initial*` properties of a widget. It was initially thought that this would  be possible via our `initialValue` etc properties, however these only work when the value has actually changed. For example, you cannot set a widgets `initialValue` to the same value twice in a row.

This has arisen in two widgets:

### Accordion Pane

In our accordion pane we need to fully control the open state of our TitlePanes. This does not work via `initialOpen` as once it has been set to `true` or `false` it cannot be set to the same value again.

### Multiselect-typeahead

When writing this widget we have noted that we need to clear the typeahead's text-input when a value has been selected. This is possible on the first change by setting `initialValue` to an empty string, however, the next time you try and do the same it does not work as the `initialValue` and stored `existingInitivalValue` are the same.

## Proposal

The proposal is to add controlled properties to shadow each of the current `initial*` properties.
Lets use `initialValue` as an example.

In most cases, we treat `initialValue` as follows:

```tsx
const { initialValue } = properties();

let value = icache.get('value');
const existingInitialValue = icache.get('initialValue');

if (initialValue !== existingInitialValue) {
	icache.set('value', initialValue);
	icache.set('initialValue', initialValue);
	value = initialValue;
}
```

We propose that a `value` property is added and that it takes precedence over the `icache` value and the `initialValue` property at all times.

eg, the above code could become.

```tsx
let { value } = properties();
const { initialValue } = properties();

if (value === undefined) {
	value = icache.get('value');
	const existingInitialValue = icache.get('initialValue');

	if (initialValue !== existingInitialValue) {
		icache.set('value', initialValue);
		icache.set('initialValue', initialValue);
		value = initialValue;
	}
}
```

This approach should allow full control to be asserted over a widget via the `value` property.
This will fix the issue we are having with `AccordionPane` and should allow the `Multiselect-typeahead` to function as desired if we were to pass the controlling property for the typeahead input down to the text-input widget being used.

**We should implement this pattern for all properties that have an `initial*` prefix**

**Comment by devpaul** [comment]
This sounds like you need imperative behavior from a declarative widget. This could be a reasonable place to use a signal pattern. I the pattern was in the Dojo Patterns roundtable document, but I don't know if we had time to get to it. This is from the doc:

**Signals**
Sometimes it’s useful to have an imperative-like interface on a widget. It is especially useful for media-based widgets: video, audio, animated characters, 3D, etc....

**Scenario**
You’ve created an animated character
Controls are walk left, walk right, stop, dance
Smooth animation requires only changing animation sequences on keyframes

**Option 1**
Externalize controls into processes and the store
Manage updates to store on a timed process and keep the next action in the store

Pros
This is a very reactive way to manage state

Cons
Forces an imperative interface into a reactive context
OK for 1 character; complex for n characters
View logic is far away from widget
Extracted view logic makes custom element (basically) worthless

**Option 2**
Pass in a signal to notify the widget of their next action
Use a pattern that notifies the widget to take an action

Multiple ways to do it:

* Pass a signal object as a property
* Pass a function that receives a handler as a property
* Pass a queue and a function that pops the queue

Pros
Signals are property-like with imperative behavior
Allows a widget to self-manage internal view-state & logic
Custom elements maintain their view logic
Supports (n) widgets

Cons
Properties are not serializable

I've done a bit of work around making imperative behavior work in declarative contexts, so I wanted to get this on your radar. There are pros/cons to both approaches. In particular using a `value` that overrides `initialValue` adds complexity by pushing the state out of the widget and disallows the widget to manage its own internal state. A signal is a way to pass transient information to a widget and is a good option for triggering internally managed state.

**Comment by tomdye** [comment]
I believe this is now complete, thanks everyone!
