### ISSUE TITLE
Fix placeholder text and label for Material themed Select

### ISSUE THREAD

**Issue by ericos** [dojo/widgets#1359]
**Bug** 

The `Select` placeholder text and label appear to be rendering atop one another in the material theme.

Can be viewed in the example app, Select -> Additional Text, with Material theme selected.

![Screen Shot 2020-04-08 at 11 18 21 AM](https://user-images.githubusercontent.com/1054198/78808661-67604980-798b-11ea-88d8-7919ada26e97.png)

**Comment by tomdye** [comment]
This is as designed, material theme does not support `placeholder` text, you are supposed to use the label or the helperText instead.

**Comment by ericos** [comment]
> This is as designed, material theme does not support `placeholder` text, you are supposed to use the label or the helperText instead.

Ah. Thanks for the clarification 👍
