### ISSUE TITLE
Calendar material theme hover styling

### ISSUE THREAD

**Issue by ericos** [dojo/widgets#1361]
**Bug** 

The `Calendar` widget needs hover state styling for the Material theme. Should follow the Material guidelines at https://material.io/components/pickers/#anatomy

Will need a new variable added for the hover color, possibly a calc lightened version of `mdc-theme-primary`

**Expected behavior:**
Hovering day, month, year selectors should have hover styling.

**Actual behavior:**
No hover styling is currently present for the Material theme.

Per Material Design guidelines, item 6 shows hover styling.
![mio-staging_mio-components_1584058305895_assets_0B54x0KDcs5U-d0dJMFg2OTdGWjg_picker-elements-desktop](https://user-images.githubusercontent.com/1054198/78815423-dfcc0800-7995-11ea-9e1e-94ff6e259a95.png)

**Comment by tomdye** [comment]
Just checked, as the background colour is applied to the `:before` element, thus should be achievable by adding an `opacity` along with the existing primary background colour when hovered. No need for a new variable.
