### ISSUE TITLE
Enhance Popups - More Positions and Better Mobile Support

### ISSUE THREAD

**Issue by jellison** [dojo/widgets#1414]
**Enhancement**

Several widgets are currently based on the `Popup` or `TriggerPopup`, which are limited to `above`/`below` placements. This makes building robust, mobile-aware - widgets more difficult.

I propose these base widgets be enhanced in this way:
- Expand positioning to support a plethora of positions like https://ant.design/components/popconfirm/.
- Refactor the incoming `position` property to be absolute (as opposed to a recommendation). The base widgets should automatically find the best position unless a `position` is explicitly set. Currently, composite widgets try to override positioning (with relative or absolute positioning) to achieve a proper fit. This change will allow composite widgets to trust the positioning and focus on implementing support for possible positions.
- Automatically turn positional popups into "modals" for mobile, similar to https://material.io/components/dialogs#alert-dialog (horizontally & vertically centered).
- (Optional) Allow the consuming widget to specify which positions it wants to support (maybe, `['top', 'bottom', 'modal']` is all they want, but still want to take advantage of the internal "best fit" positioning).

**Comment by samends** [comment]
Alright from your description it seems like the requirement for this issue should be:
- Adding the position options of `right` and `left` to the popup widget and updating the auto placement feature of the `Popup` widget to reflect those new positions

I've made a separate issue for turning popups into modal on mobile: https://github.com/dojo/widgets/issues/1504
