### ISSUE TITLE
Dojo Grid returning incorrect details from 2nd page onwards

### ISSUE THREAD

**Issue by kiranallari** [dojo/widgets#1436]
**Bug / Enhancement** 
Dojo Grid returns the incorrect selected data from 2nd page onward
The bug can be reproducible here - https://dist-5qhc8bqm4.now.sh/
select any row in first page and go to next page and click on any row and notice the grid is not returning the selected row details instead returning row details always from first page.

Package Version: 6.2.0
**Code**
click here for source code -  
(https://github.com/dojo/framework/files/4545461/dojoGrid_src_code.zip)

Click here for explanation about the bug   
(https://github.com/dojo/framework/files/4545460/Dojo.Grid.Issues.docx)

**Expected behavior:**

Grid should return the selected row details

**Actual behavior:**

Grid returns always the details from page 1

**Comment by kiranallari** [comment]
I have mentioned two issues in the grid , one is - selected value is not returned by grid from 2nd page onwards , i guess  you have fixed it ,I could see in the screenshot .

Second issue is -  Grid still shows selection in 2nd page also though user has not selected any row in page2 . Selection remains same . Kindly fix second issue also.

Thank you very much for all your support and quick help on this..

**Comment by kiranallari** [comment]
Hi,
We need to apply this fix as early as possible. Would you please update on this.
Thanks for your support.

**Comment by agubler** [comment]
Good Afternoon @kiranallari, the changes have been approved today and will likely get merged in to master this week. Once they have been merged in then we'll be looking to back port this for v6.2.0, likely to be in the next week or two.

**Comment by agubler** [comment]
@kiranallari This has been released on v6.2.1, please check it out. Thanks @bitpshr.
