### ISSUE TITLE
RangeSlide behavior is erratic with default Dojo theme

### ISSUE THREAD

**Issue by dylans** [dojo/widgets#1477]
**Bug / Enhancement** 

When using the RangeSlider with the default Dojo theme inside Dojo Parade the behavior in dragging and clicking is erratic and unexpected. This is true with Firefox, Chrome, and Safari on macOS. Switching to the Material theme results in the widget behaving in the expected manner.

Package Version: 7.0

**Code**

https://widgets.dojo.io/#widget/range-slider/overview

**Expected behavior:**

RangeSlider moves with dragging or clicking in a predicable manner.

**Actual behavior:**

RangeSlider becomes unresponsive to mouse click and drag events at times, jumps around in unexpected ways, etc.

See https://www.dropbox.com/s/r9adlfu9tfn6o9x/rangeslider.mov?dl=0

**Comment by jellison** [comment]
Looks like two separate underlying issues with the Dojo theme:

**Incorrect Input Height**
The input height - which captures user input - is only 1px high making interaction difficult.

_Dojo_
![image](https://user-images.githubusercontent.com/41762295/84807518-5b20ea00-afd5-11ea-9421-9c7e05d5d3a3.png)

_Material_
![image](https://user-images.githubusercontent.com/41762295/84807581-75f35e80-afd5-11ea-9670-ba790b112f9d.png)

**Incorrect Thumb Position**
The thumb position is missing a negative 50% margin to re-center the thumb over the correct position.

_Dojo_
![image](https://user-images.githubusercontent.com/41762295/84807713-a6d39380-afd5-11ea-846e-3d539264945a.png)

_Material_
![image](https://user-images.githubusercontent.com/41762295/84807727-acc97480-afd5-11ea-9a38-3d33335586d6.png)

**Comment by dylans** [comment]
Thanks @jellison, that seems consistent with my experience. It's probably worth checking if the same issues exists on the normal Slider widget as well.
