### ISSUE TITLE
Input widget labels are inconsistent and mis-documented/undocumented

### ISSUE THREAD

**Issue by bitranch** [dojo/widgets#1496]
dojo/widgets 7.0.0

I've been trying to make sense of how labels are used with input widgets in Dojo v7. I ended up creating a table to help figure out what's what. As a side-effect, I discovered a number of issues.

| Widget | Label format  | Notes  |
|---|---|---|
| Checkbox | child | |
| CheckboxGroup | named | |
| ConstrainedInput | named | |
| DateInput | -  | label not supported?  |
| EmailInput | named | label undocumented |
| NativeSelect | child | |
| NumberInput | named | label doc'd as *property* (undocumented otherwise) |
| PasswordInput | named | label undocumented |
| Radio | child | |
| RadioGroup | named | |
| RangeSlider | named | label doc'd as *property* |
| Select | named | label doc'd as *property* |
| Slider | named | label doc'd as *property* |
| Switch | named | label doc'd as *property* |
| TextArea | child | label doc'd as *property* (undocumented otherwise) |
| TextInput  | named  | label doc'd as *property* |
| TimePicker  | named  | `{label}` is the only child  |
| Typeahead | named | label doc'd as *property* |

**Note<sup>1</sup>**: A named label is an object child in the form of `{ label }`. A child label is a single unnamed `RenderResult`.

**Note<sup>2</sup>**: Where `label` is documented as a property, it usually occurs in the **Accessibility Features** section.

**Note<sup>3</sup>**: (From Dojo Discord, 16-Jun-2020)
*bitranch*: To be consistent with other input widgets, shouldn't `Radio` and `Checkbox` accept a `{label}` child?
*tom*: [B]oth `Radio` and `Checkbox` accept a `RenderResult` as their child which is used as the input label. We only use an object for children when there is more than one named child.

----

### Documentation

Documentation for `label` across the majority of input widgets is obviously incorrect or missing. I checked the documentation against both `widgets.dojo.io` and the source readme files.

### Consistency

From the #780 guidelines section:

> Prefer simplicity and single, consistent ways of doing A Thing

I assumed things like `label` would fall under that "single, consistent ways" part, but the label inconsistency appears to be by design (see Note<sup>3</sup> above). Also note that `TimePicker` violates the single-child design decision, so not even that is consistent.

The side-effect is that you need to know the implementation of an input widget before you can guess at how to set the label. It's not a very user-friendly API in this case. I'd suggest making all input widgets consistently use a `{label}` child.

**Comment by tomdye** [comment]
complete via https://github.com/dojo/widgets/pull/1497
