### ISSUE TITLE
ComboBox: Add Functional Tests

### ISSUE THREAD

**Issue by eheasley** [dojo/widgets#151]

**Comment by mwistrand** [comment]
I have a number of tests that pass beautifully in Chrome and iPhone, but have hit the following walls:

* When sending non-character keys (tab, arrow keys, etc.) to the combo box input, `FirefoxDriver` adds odd characters to the input. I have not been to able to track down an official issue for this yet.
* Sending arrow keys to the combo box input with `SafariDriver` causes the results menu to close, although I have yet to determine what is causing this. Behavior is correct in actual Safari.
