### ISSUE TITLE
Typeahead shows result popup when there are no results

### ISSUE THREAD

**Issue by msssk** [dojo/widgets#1527]
**Bug** 

Package Version: 7.0.2

**Expected behavior:**

Typeahead should not show popup when there are no results

**Actual behavior:**

Empty popup that displays as a thick horizontal line shows below text input

1 - initial render of Typeahead
![typeahead1](https://user-images.githubusercontent.com/931637/90572089-0e3dc900-e168-11ea-9981-0559f5967a6d.png)

2 - Typeahead with a single result in the popup
![typeahead2](https://user-images.githubusercontent.com/931637/90572109-18f85e00-e168-11ea-9e58-59c7f1481a06.png)

3 - Typeahead with no results, but empty popup is still displayed
![typeahead3](https://user-images.githubusercontent.com/931637/90572130-23b2f300-e168-11ea-9205-23602f57f61e.png)

**Comment by tomdye** [comment]
@msssk it looks like you're using a custom theme there and are rendering a 1px border on your popup contents even when it has no results. This results in the 2px line you are seeing. I believe this is a problem in your own code and not with dojo widgets as it does not occur when using the default / dojo / material themes.

**Comment by tomdye** [comment]
@msssk I took a look at your skills matrix PR and it looks like this is your offending line: https://github.com/dojo/examples/pull/403/files#diff-8caa5b736c8bab2e440ad6597eafd48cR61

The `menuWrapper` dom node is a placeholder for the list and is always rendered regardless of the number of results. You'll want to change that line to apple the `menu` class to the `List` `root` instead.

**Comment by msssk** [comment]
This is still an issue. I don't see a way to provide a border around the results popup. None of the available themes does so (which often looks weird - try deleting the code example below the typeahead input and when you no longer have the stark contrast of a white popup over a dark code block the lack of a border around the results popup is very noticeable).

**Comment by tomdye** [comment]
@msssk the list can be targetted via the `menuRoot` class on the `Typeahead` but I believe the underlying issue you are experiencing is related to the `List` itself rendering when it has no items. I have raise an issue to track this inplace of this issue here: https://github.com/dojo/widgets/issues/1530
