### ISSUE TITLE
`onValidation` is called with `true` or `false` before the text input is dirty

### ISSUE THREAD

**Issue by maier49** [dojo/widgets#1549]
**Bug** 

As can be seen in the [validated text input example](https://widgets.dojo.io/#widget/text-input/example/validated) and others, the validation status is being updated before a user interacts with the input. While the behavior is correct if `valid` is explicitly set to `undefined`, it appears that `onValidate` gets called more than once, eventually with `true` or `false` depending on the widget's validation settings, updating the icache and displayed validation status.

**Code**

**Expected behavior:**

Validation success/failure should not be displayed until after it's edited
**Actual behavior:**

It is displayed immediately

**Comment by agubler** [comment]
This has been resolved by https://github.com/dojo/widgets/pull/1640
