### ISSUE TITLE
Material header text is the wrong colour against the background

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#1554]
**Bug** 

Current material header title / action text is black when it should use the appropriate primary-on-dark variable.

<img width="640" alt="Screenshot 2020-10-15 at 16 54 54" src="https://user-images.githubusercontent.com/814453/96154841-28491d00-0f07-11eb-956f-384c6a019366.png">

**Comment by agubler** [comment]
I think this has been resolved, @tomdye can you confirm and close?

**Comment by agubler** [comment]
fixed by https://github.com/dojo/widgets/pull/1553
