### ISSUE TITLE
DateInput widget not working with browsers set to date formats other than 'dd/mm/yyyy' or 'mm/dd/yyyy'

### ISSUE THREAD

**Issue by arndbeissner** [dojo/widgets#1563]
**Bug** 

The DateInput widget will by default adopt the date format the browser is currently set to. When your date format is "dd.mm.yyyy" like in many EU countries, the DateInput widget will format the date in that format, but it will show the validation notice: "Invalid date format".

What I found:

1) There is no extension point yet to add DateFormats.

2) The widget uses the "Intl" builtin for date formatting (that's why the date shows up in the proper format). But the widget uses its own regex validation parsing in date-utils. Since date-utils only supports ISO and "dd/mm/yyyy" (plus the US version of it), you have a mismatch whenever your browser is set to something else.

3) We didn't get it to work with ISO either - because you can't tell it to just use ISO, you would have to configure the browser to deliver ISO from the Intl api by default. 

For completeness sake: tested in Chrome/Safari on MacOS and Chrome/Firefox on Windows

Package Version: @dojo/widgets 7.0.3

**Code**

Set your browser to a date format like "dd.mm.yyyy" - anything that isn't 'dd/mm/yyyy' or 'mm/dd/yyyy' and open the widget test page: 

https://dojowidgets-git-list-typeahead-filtering-select-behaviour.dojo1.vercel.app/#widget/date-input/overview

**Expected behavior:**

Date is displayed in browser locale date format and validates.

**Actual behavior:**

Date is displayed in browser locale date format but does not validate.

<img width="709" alt="DateInput" src="https://user-images.githubusercontent.com/11542115/99444648-c96b2f00-291c-11eb-9ed3-394acfb31c0b.png">

**Comment by arndbeissner** [comment]
Note that without a fix the entire widget is unusable if the browser is not set to US or UK date format. 

The reason for the bug is that the widget uses the Intl API for some things, but also uses its own regex based validation for date format validation. And there, only UK, US and ISO are implemented, plus there's no extension point to add your own. So any date value you put in will fail. I would even live with ISO format, just that you can't tell the widget to use ISO instead of the browser default. 

As for fixing it, I think this needs a decision on how you want to do I18N outside of translation in general. Sure, a small extension point for adding validation regexes would fix the issue to at least not be a showstopper. But clearly that's not the strategic answer.

**Comment by tomdye** [comment]
I believe this is limited by the regex that we are using. This will need investigating further

**Comment by aciccarello** [comment]
There are a lot of [possible Date formats](https://en.wikipedia.org/wiki/Date_format_by_country) to support beyond the 4 mentioned above so supporting all formats would be difficult (see below for a sample). I think adding a property for a `(input: string) => Date | undefined` date parser function would be the best flexibility while still having a default built-in date parser. The ISO date format should still have worked though since it should try multiple expressions.

Assuming the date parsing property is added, there is still a question of what should be the default. I see a few options:

1. Keep the existing default parsing behavior with no modifications
2. Add a few common (threshold needs to be defined) formats that we'll attempt to support by default
3. Defer to the inconsistent/implementation-dependent `Date.parse()` on everything and use it to determine if a date input is invalid

```javascript
const date = new Date(2018, 5, 1);
// Results below assume UTC timezone - your results may vary

console.log(new Intl.DateTimeFormat('en-US').format(date));
console.log(new Intl.DateTimeFormat('fr').format(date));
console.log(new Intl.DateTimeFormat('be').format(date));
console.log(new Intl.DateTimeFormat('zh').format(date));
console.log(new Intl.DateTimeFormat('nl-NL').format(date));
console.log(new Intl.DateTimeFormat('sl').format(date));
```

> "6/1/2018"
> "01/06/2018"
> "1.6.2018"
> "2018/6/1"
> "1-6-2018"

**Comment by arndbeissner** [comment]
It seems that the Intl API library isn't going to implement the string->Date direction anytime soon (https://github.com/tc39/ecma402/issues/342). I would have expected at least as strict conversion for that direction in the pipeline. 

From a result perspective, I could live with 1, 2, and 3. However, in all of the cases, the following should be fulfilled:

From a Dojo user's perspective, I would expect a Date widget to behave consistently. It should either deal with a locale properly or tell me that I need to supply a custom function to inject functionality and/or fall back to a default. What it should never do is silently accept a Date value, handle it properly on the output side, but not on the input side. Right now it will take the value, format it properly, yet say: "this is not valid" on validation.
