### ISSUE TITLE
Leading child breaks number input in the material theme

### ISSUE THREAD

**Issue by agubler** [dojo/widgets#1578]
**Bug** 

The `leading` child for the NumberInput in the material theme breaks the `NumberInput` widget but works fine in the dojo theme

Package Version: 7

<img width="672" alt="Screenshot 2020-11-20 at 12 39 41" src="https://user-images.githubusercontent.com/1982678/99801167-7f0ccc80-2b2d-11eb-8450-7f796da0c69f.png">

**Comment by aciccarello** [comment]
I wasn't able to reproduce this issue. I'm opening a PR with a Leading/Trailing NumberInput example which I've used to test.
