### ISSUE TITLE
Update animations for LoadingIndicator widget

### ISSUE THREAD

**Issue by samends** [dojo/widgets#1584]
**Enhancement** 

It would be helpful for a developer to have a loading widget that has a property value that would change the type of spinner animation as needed. The update could involve adding the property value of `type` to the `LoadingIndicator` widget that could have the basic values `linear` and `circular` as described here: https://material.io/components/progress-indicators#types as well as some others. Some examples I found are:

- https://spin.js.org/
- https://loading.io/css/
- https://ant.design/components/spin/

**Comment by tomdye** [comment]
Adding a `type` property to the loading indicator may well make sense here.

**Comment by tomdye** [comment]
https://material-ui.com/components/progress/
https://material.io/components/progress-indicators#usage
