### ISSUE TITLE
Add VStack and HStack components

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#1585]
**Enhancement** 

Add VStack and HStack components for laying widgets out horizontally and vertically. This widget has been argued against in the past because "it's 1 line of css in flex", but that ignores the fact that these components would be able to apply padding and margin specific to a theme for the user as well.

**Comment by agubler** [comment]
As well providing standardised margin and padding for themes HStack and VStack components could also be used with a third component that will use all the remaining "flex" space. This will allow specific but responsive positioning of components either vertically or horizontally, plus enable placing multiple components all with the same space.
