### ISSUE TITLE
What is the difference between the title property and the header child property

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#1587]
**Bug** 
They both appear to do the same thing, although `title` is limited to a string. Is `title` needed at all?

**Comment by tomdye** [comment]
If i remember correctly, the title is the styled title text that displays as the title of the card, however the `header` goes at the top of the card, and in the case of a media card, is above both the title and the media image.
This can be seen here: https://widgets.dojo.io/#widget/card/example/cardcombined
