### ISSUE TITLE
Icon Button is not positioned correctly

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#1594]
**Bug** 
Especially bad for material theme. See below: 

<img width="145" alt="Screenshot 2020-11-30 at 13 11 31" src="https://user-images.githubusercontent.com/2183490/100614207-afaeec00-330d-11eb-8507-cc5953a91df6.png">

https://widgets.dojo.io/#widget/icon/example/iconbutton

**Comment by matt-gadd** [comment]
Should this be a dedicated variant of the button widget? or a child on the button widget maybe?

**Comment by aciccarello** [comment]
Doing this as a variant of the button widget seems difficult since each type of button could have an icon. I'm updating the styles to keep everything centered and updating the example to use small icon size (which is more in line with material standards).
