### ISSUE TITLE
Should the list automatically set the first selected item?

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#1609]
**Bug**

At the moment if you create a `List` the first option is always selected if no value is set. For the `Listbox` html element, if no value is set no option is highlighted which seems the more correct behaviour?

**Comment by tomdye** [comment]
I believed this may be related to https://github.com/dojo/widgets/issues/1655

**Comment by agubler** [comment]
@tomdye I'm not sure that's related, I believe it's just that the list highlights the first item by default not actually selected - perhaps @matt-gadd can clarify?
