### ISSUE TITLE
Autocomplete messes with floating label styles like those in Material

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#1610]
**Bug** 

<img width="384" alt="Screenshot 2020-12-07 at 13 34 52" src="https://user-images.githubusercontent.com/2183490/101357249-180f4780-3891-11eb-8b74-c2fa0a9e9307.png">

Apparently this can be fixed with a transition to trigger js via the ` :-webkit-autofill` pseudo (e.g https://codedaily.io/tutorials/69/Animated-Input-Label-with-Chrome-Autofill-Detection-in-React).

**Comment by aciccarello** [comment]
## Reproducing the Issue
I have tested this in Chrome 88, Chrome Canary 90, or Safari 14. In Chrome the overlapping is only when the user hovers over the fill. Once a fill option is selected using the keyboard or mouse clicks, the label for all filled in fields moves to the correct position. I haven't been able to test this with a login form. Is there some issue happening even after the autofill is selected?

https://user-images.githubusercontent.com/11273838/107719340-dafa7380-6c8c-11eb-9741-b505765023bd.mov

## Fix
I did start working on the fix of keyframes to see if I could get the label to move when chrome shows a preview of the fill data. In testing that, it seem that the animation isn't triggered until the option is selected though at one point I thought I saw the event getting triggered before. The other issue I ran into is that css-modules localizes the keyframe name so if we need to differentiate the start and cancel animations, we'll need to import the name.

https://user-images.githubusercontent.com/11273838/107721648-f74cdf00-6c91-11eb-904a-49bb04237e5a.mov

**Comment by aciccarello** [comment]
For future reference, the way I manually tested this was by modifying the examples page:
1. move the material theme to the [first (default) position](https://github.com/dojo/widgets/blob/5d8bb32fd60a20a6fd414c04b52e78da783365e4/src/examples/src/config.tsx#L304-L305)
2. Make an example page have a login form with a submit button (example below)
3. Open chrome and enter some fake credentials and hit submit. It should show a key icon which you can use to save the credentials.
```tsx
		<Example>
			<Form>
				{(form) => {
					return (
						<FormGroup>
							<FormField>
								<TextInput key="username">
									{{ label: 'Username' }}
								</TextInput>
							</FormField>
							<FormField>
								<PasswordInput name="password">
									{{ label: 'Password' }}
								</PasswordInput>
							</FormField>
							<Button key="submit" type="submit">
								Submit
							</Button>
						</FormGroup>
					);
				}}
			</Form>
		</Example>
```
