### ISSUE TITLE
Unit Test Warnings

### ISSUE THREAD

**Issue by samends** [dojo/widgets#1641]
**Bug** 

When unit tests are run for the widgets with `npm run test` the following warning message is logged

```
The array API (`children: DNode[]`) has been deprecated. Working with children should use a factory to avoid issues with mutation.
```

The tests should probably be updated to use the newest dojo testing apis so that these warnings don't appear.

Package Version: 8.0.0-pre

**Comment by agubler** [comment]
Resolved by #1691
