### ISSUE TITLE
Select isn't validating initial value

### ISSUE THREAD

**Issue by rorticus** [dojo/widgets#1653]
`Select` is reporting false validity when using an initial value.

https://codesandbox.io/s/distracted-meadow-2tdj1?file=/src/main.tsx

Click the select box to open it and then closing it will cause validity to report true.

**Comment by samends** [comment]
Found an additional problem with `Select` not initializing a dataset gotten from a dojo resource it there is a initial value set #1654 this could maybe be worked on in the same update

**Comment by samends** [comment]
Seems to only be returning false if you use `field('select', true)` with the select field. If you use the conventional `required={true}` on the `Select` widget it seems to work https://codesandbox.io/s/romantic-johnson-f3z6v?file=/src/main.tsx

**Comment by samends** [comment]
Seems to be the form middleware that could be the cause of this, I suspect the form middleware somehow doesn't evaluate the required values set by `field()` going to look into this further
