### ISSUE TITLE
Select disabled colour does not match other inputs in material

### ISSUE THREAD

**Issue by agubler** [dojo/widgets#1684]
**Bug**

The disabled colour of the `Select` widget does not match other inputs

<img width="638" alt="Cursor_and_maya-consent" src="https://user-images.githubusercontent.com/1982678/110776792-5897ac00-8258-11eb-9079-a2ba7808019e.png">

Not checked the dojo theme, should verify that too.

**Comment by bitpshr** [comment]
Fixed by ser @tomdye.
