### ISSUE TITLE
Widgets README

### ISSUE THREAD

**Issue by agubler** [dojo/widgets#19]
**Enhancement**

Now we are starting to get a few completed components, we should think about the Widgets README in terms of the details and structure needed.

**Comment by rishson** [comment]
I think we are OK with the README for beta 1, but for beta 2, we need to include:

- code examples of using the uber package
- code examples of using a standalone widget (individually published to npm)
- Link to a gallery page that shows all the widgets written so far, what they look like etc
 - detailed explanation of `a11y` and `i18n`
- detailed explanation of the themes available and how to switch
- detailed explanation of how to write your own theme

@agubler anything missing from the list?

**Comment by bitpshr** [comment]
It may also be good to demonstrate extending one of our components.

**Comment by rishson** [comment]
Maybe we should also explain the naming conventions that we use within widgets, such as `onRequestX` for externally handled changes.

**Comment by rishson** [comment]
- [ ] code examples of using the uber package
- [ ] individual widget READMEs with link on main page 
- [ ] link to a gallery page that shows all the widgets written so far, what they look like etc
- [ ] document event handler naming conventions
- [ ] document extending a widget
