### ISSUE TITLE
More granular control of property assignment

### ISSUE THREAD

**Issue by pottedmeat** [dojo/widgets#202]
**Enhancement**

The widget lifecycle currently has no way to define how properties are stored for later comparison. Currently, comparison may be customized using `diffProperties(previousProperties)` but `internalState.previousProperties` will always make a full copy of `instance.properties`.

By introducing a hook that would allow the widget to decide what properties are stored and what values they are stored with, we could significantly decrease the overhead of property serialization with `deepAssign` and give widgets increased flexibility in making decisions about property change detection.

We should decide whether this hook should allow widget authors to use reference comparison as a valid way of comparing property values. I would argue this should be allowed, though designed in such a way as to encourage a more specific method of value comparison.

**Proposal**

* Add a new method alongside `diffProperties` and `applyChangedProperties` that will take the current properties and return the keys and values that should be used for comparison.
* Change `diffProperties` to accept the previous properties and the result of this new method as its current properties. If the widget author wanted to also use the original properties, they would be available using `this.properties`.
* Create a wrapper function for storing values by reference using something like a `WeakMap` that stores symbols or otherwise unique objects keyed by these instances so that two calls to this function with the same instance would return identical values.
* Continue using something like `deepAssign` when storing to `interrnalState.previousProperties` with the exception of leaving these wrapped references intact.

**Comment by matt-gadd** [comment]
@pottedmeat going to close this as I believe #212 resolves the majority of this issue. feel free to reopen if it doesn't! 😄

**Comment by pottedmeat** [comment]
I was able to make some great improvements to dgrid with this but eventually ran into areas where I don't quite have enough control over the lifecycle of the properties. Reading through what I wrote above, I was unclear about the details of this.

## When `properties != previousProperties`

Let's say I have an object where every change to the object results in the increase of an internal counter stored under the `version` key. I'd still like the full object to be accessible by the rest of the code through the `properties` key but I'd like to store just the `version` value in `internalState.previousProperties` for later comparison.

With the current API, there is no way for me to leave the object intact on `properties` while saving a serialized/hashed/versioned piece of data in `internalState.previousProperties`

## When Calculating a Diffable Value is Expensive

In the case where an object I'm working with is complicated enough where the serialized/hashed value is the result of a significant amount of logic/memory/processing power, the current API would require this value be calculated twice.

1. In `diffProperties`, I would need to calculate the value to compare to `previousProperties` in order to return the keys that have changed. I would not be able to assign this value to `newProperties` as it would override the actual value.
2. In `assignProperties`, I would need to calculate the value to be stored in `inernalState.previousProperties` so that I may later compare its value with a new calculated value.

**Comment by matt-gadd** [comment]
@pottedmeat this is great, I think over the weekend/today me and @agubler have potentially already solved these conceptually with some alignments of diff and assign (to 1 function) and per property lifecycle handling. issue incoming that I will link to.

**Comment by pottedmeat** [comment]
One further thing to add, now that you've gotten the idea in my head of managing properties individually is that there are some cases where I want to know if a set of properties related to a general set of functionality has changed.

In this case, I've been integrating the grid pagination functionality and, while knowing whether the data, sort options, or underlying store have changed is useful to the bits of the grid that consume those pieces of data – all the pagination cares about is if one of them has changed without needing to know which or have access to those pieces of data. A simple dirty flag or version increment would be just fine I think.

**Comment by matt-gadd** [comment]
I think the issues in this issue are now solved by the granular control of properties here: https://github.com/dojo/widgets/pull/253.
