### ISSUE TITLE
Observe all for createMemoryStore

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#21]
Their is currently no way to observe all items on the memory store.

**Comment by kitsonk** [comment]
Correct...  That is one of the proposed enhancements to be addressed in defining the [store Observation API](https://github.com/dojo/stores/issues/1).

Is it a limiting anything at the moment?

**Comment by matt-gadd** [comment]
@kitsonk not particularly, we just implemented it in todo-mvc for now.

**Comment by kitsonk** [comment]
Then are we fine closing in favour of dojo/stores#1?

**Comment by matt-gadd** [comment]
@kitsonk yup thanks 👍
