### ISSUE TITLE
i18n in widgets

### ISSUE THREAD

**Issue by smhigley** [dojo/widgets#213]
**Enhancement**

We need to figure out how to handle nls files for widgets that have internal string. I can see a couple different possibilities:

1. Keep everything within each individual widget
2. Put nls files in `widgets/common`, which may result in less code duplication for things like months or weekday names that could appear in multiple widgets
3. Leave it up to widget users to provide translations and pass them in via properties. This seems like a little too much work for end users, though.

**Comment by dylans** [comment]
I would vote for 2 as the default.

**Comment by tomdye** [comment]
Vote for 2

**Comment by rishson** [comment]
Can I get some more info here please? Taking `Calendar` as an example, are you suggesting:

1) `widgets/src/calendar/i18n/en/Calendar.ts`, `widgets/src/calendar/i18n/fr/Calendar.ts` ..
2) `widgets/src/common/i18n/en/Calendar.ts`, `widgets/src/common/i18n/fr/Calendar.ts` ..
3) free for all

?

**Comment by smhigley** [comment]
@rishson I think something along the lines of `widgets/src/common/i18n/en/Widgets.ts`, but I don't feel qualified to be the one to make that decision. I think @mwistrand would know better than me :)

**Comment by mwistrand** [comment]
I would personally prefer something similar to what we do for CSS: widget-specific messages are contained by the widget's directory, and any common messages go under `src/common`. While there is no hard rule (yet), elsewhere we have maintained the Dojo 1 convention of using an `nls` directory to house localized messages, so `widgets/src/calendar/nls/`. Also, assuming English is the default, those messages would not go under an `en` directory, but directly underneath the `nls` directory: `widgets/src/calendar/nls/main.ts` or `widgets/src/calendar/nls/Calendar.ts`.

**Comment by smhigley** [comment]
@mwistrand that sounds good to me! So, using the Calendar as an example, would the weekday names and month names go in `src/common/nls`, while the Calendar-specific labels (e.g. "Choose Month") go in `src/calendar/nls`? Also, what should we do for file names and organization in `src/common/nls`?

**Comment by rishson** [comment]
`src/common/nls/Widgets.ts` with:

```
const messages = {
    daysOfWeek: {
	monday: 'monday',
        ...
    },
    ...
};
export default messages;
```
then

`src/common/nls/de/Widgets.ts` with:

```
const messages = {
    daysOfWeek: {
	monday: 'montag',
        ...
    },
    ...
};
export default messages;
```

then `src/calendar/nls/Calendar.ts` with:

```
const messages = {
    chooseMonth: 'Choose month',
    ...
};
export default messages;
```
?
