### ISSUE TITLE
HTML attributes

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#22]
I believe @Tomdye has raised this before, but when using `createCachedRenderMixin` their seems to be no other way than completely overriding `getNodeAttributes` for providing HTML attributes other than `classes` and `styles` (which have nearly identical `getters` and `setters`). Perhaps we should have a more generic `attribute` map?

**Comment by kitsonk** [comment]
As I discussed with @Tomdye that is incorrect, you can aspect `getNodeAttributes`:

```typescript
const createEnhancedAttributesMixin = createCachedRenderMixin
    .before('getNodeAttributes', (overrides?: VNodeProperties) => {
        overrides = overrides || {};
        /* do something interesting */
        return [ overrides ];
    });
```

I am really reticent to provide a generic `attribute` map, as that will generally just be a 👣 🔫. Other mixins should provide structured access to any variables, deriving them from state.  Widgets should be specific about how the augment the behaviour of how things get rendered.  Is there another pattern that provides some level of structure instead of an indiscriminate `attribute` map?  Is there a reason why the AOP is not a viable pattern?

**Comment by matt-gadd** [comment]
@kitsonk i'm neither for or against the aspect. but if that is the thinking then I don't believe `classes` or `styles` should have getters/setters? Why are they special cases? (other than `classes` having a transform from an `array` to a `map`).

**Comment by kitsonk** [comment]
> i'm neither for or against the aspect. but if that is the thinking then I don't believe `classes` or `styles` should have getters/setters?

But that is the point, the mixin exposes them in a structured way, versus an indiscriminate way, where the way of expressing them in the widget's state is clear and deterministic.  The listeners are handled in a similar fashion, thought not directly exposed, as well as the widget ID attribute.  If the changes are generally useful to all widgets, we should propose to modify `cachedRenderMixin`, if it is specific to a class of widget, then we have an AOP pattern to modify behaviour.

Are there other DOM attributes that should be available and how best to expose them externally?

**Comment by matt-gadd** [comment]
Regardless of being indiscriminate or not - why are `classes` and `styles` special (is it usage?!)? and why should the `cachedRenderMixin` care? at the very least the code for the getters/setters is identical apart from the `classes` transform, which kind of hints this is going to be an extremely common bit of code for any HTML attribute.

**Comment by Tomdye** [comment]
I thought we discusses added specific HTML attributes with types setters and getters for certain widgets. Ie. `TextInput` should accept `readOnly`,`placeHolder` etc...

**Comment by kitsonk** [comment]
> why are `classes` and `styles` special (is it usage?!)?

Why are `id` and `listeners` special?  They were attributes that were identified that had logical way of expressing them in the widget's state object and rendering them in a consistent fashion and we identified the rules of which they would be governed by and how to expose them.

> which kind of hints this is going to be an extremely common bit of code for any HTML attribute

Possibly... What other common attributes are there?

**Comment by kitsonk** [comment]
> I thought we discusses added specific HTML attributes with types setters and getters for certain widgets. Ie. TextInput should accept readOnly,placeHolder etc...

Correct... and suggested we could revisit the way CachedRenderMixin made it easier to add those in, but wanted to avoid unfettered access to a options bag for attributes.

**Comment by kitsonk** [comment]
For example, [ResizePanelMixin](https://github.com/dojo/widgets/blob/aa9fcdc80cd506cde4ee8c73099b65894e38d993/src/createResizePanel.ts#L163) uses aspect after to augment the node attributes in line with the exposed API.

If there are generally applicable, they go in CachedRenderMixin, if they are specific to a class/mixin, they go in the mixin and apply the appropriate rendering logic.

**Comment by matt-gadd** [comment]
so whats `generally applicable`? https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

**Comment by Tomdye** [comment]
Fair point @matt-gadd , the list would be very hard to maintain. What would be the real harm in allowing a pass through for `HTMLAttributes` ?

**Comment by kitsonk** [comment]
> so whats *generally applicable*?

In my mind, it was something that was instance based that was applicable to any element.  It is arguable that `styles` should be removed, as we want to discourage inline styles and the only widget so far that uses it does not use the state to persist it.  `classes` was a bit different, where you could often see a use case where a class could potentially be specified to modify the styling of an instance without creating a new class and that logic could potentially be hard to express.

> the list would be very hard to maintain

No, if we have a way of expressing what widget logic determines what rendering logic.  For example, `tabIndex`, wouldn't it be better to create some sort of logic in how that is handled, like a `tabIndex` manager mixin?  If people want to write HTML, they probably shouldn't be using a widgeting system. `accesskey` should be managed by accessibility mixins or some sort of key manager mixin.  `contextmenu` should be something totally different and managed if used at all. `dir` is the domain of i18n and specifying that on a DOM node shouldn't be directly accessible to the widget. `hidden` is a stupid attribute. `lang` again i18n. `title` potentially, though it is a11y really.  `translate` is i18n/a11y.  Same for all the `aria-*`.  Not that difficult to maintain.

> What would be the real harm in allowing a pass through for `HTMLAttributes` ?

Then the widgeting system becomes the Visual Basic of widgeting systems.  What functionality are you trying to accomplish? We can discuss the right pattern to abstract that functionality in an organised fashion.  It promotes crappy unmaintainable patterns, where someone f's you over by hacking on an instance.

**Comment by kitsonk** [comment]
Based on the [comment](https://github.com/dojo/widgets/pull/29#issuecomment-237272680) I am going to create a PR that follows that pattern.  Essentially what we will have is a situation where mixins can express functions that will return attributes that then get rendered.
