### ISSUE TITLE
Uniform validation approach for form components

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#22]
We need to consider if we plan to add mandatory and status indicators to our form fields.

By 'mandatory' I mean the usual '*' denotation for 'this form element must have a value'.
By 'status' I mean an indicator in/by the field to show that the current value is valid, e.g. [here](http://jamiewilson.io/corpus/#forms).

If we include these indicators, then some things to bear in mind:
- These indicators should not adversely impact `a11y` support.
- We need to consider how we would implement if we also allow for [addons](https://react-bootstrap.github.io/components.html#forms-input-addons) - see [also](https://react-bootstrap.github.io/components.html#forms-validation) 
- We need to consider a 'wait state' for status (if validation of the current value is async).

**Comment by rishson** [comment]
@smhigley keen to get your thoughts on this.

**Comment by dylans** [comment]
We should probably get this done before beta? @rishson and @smhigley

**Comment by smhigley** [comment]
@dylans it's in the latest PRs, but mostly just using color. I'd like to go back and add icons, now that we've talked about how to add them, but I wonder if those and other more complex styles should go in themes.

**Comment by bitpshr** [comment]
I updated the title of this ticket so we can address a general approach to validation here beyond just styling. We should make sure all form components follow the same approach. My current thinking:

A parent component should handle validation of child form components whenever it wants to by using appropriate hooks such as `onChange`. The parent component can use any logic to determine if a child form component value is valid, and if it's not valid, the parent can set `invalid` to `true` on the respective child. I also think that an optional `invalidMessage` could be useful for per-component error messaging. We can use tooltips once we have a proper component to show inline messaging.

**Comment by smhigley** [comment]
@bitpshr +1 for the `invalidMessage`. I wonder if form widgets should actually just allow the parent to pass in a DNode for the error message to allow tooltips and whatever else.

The parent component is probably going to be a form widget, so it might be good to add specs for that, and how we want consumers to specify things like validation functions and error messages.

**Comment by bitpshr** [comment]
Agreed. For now, I think the main thing to keep consistent is programmatic and styling support for `required` and `invalid` for all form components.

**Comment by rishson** [comment]
Agreed. Just for reference thought, potentially add `hintMessage` for when helper text is too large to be used as placeholder text (often seen in material design directly below a field)?

```
email:  [yourname@yourcompany.com     ]*
        (we promise not to spam you).
```

**Comment by bitpshr** [comment]
This functionality is more argument for a form mixin again :) Lots to manage for each component...

**Comment by kitsonk** [comment]
References dojo/dojo.io#136

**Comment by tomdye** [comment]
This is covered in https://github.com/dojo/widgets/issues/616
