### ISSUE TITLE
Fix Tab type in TabPane

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#220]
**Bug** 

Grunt dist not currently working due to wrong `Tab` type

**Comment by agubler** [comment]
FYI it wasn't because it was the "wrong" `Tab` it was because the type that was created `type Tab = WidgetBase<TabProperties>` was not exported.

Causing: `src/tabpane/TabPane.ts(43,75): error TS4020: 'extends' clause of exported class 'TabPane' has or is using private name 'Tab'.`
