### ISSUE TITLE
Implement the base theme

### ISSUE THREAD

**Issue by eheasley** [dojo/widgets#227]
The base theme should be applied to the widgets via their default `css`. This will require classes to be split into both `themeable` and `fixed` classes.

**Comment by kitsonk** [comment]
We should close this issue if this is completed.  If not, let's delineate what needs to be done.

**Comment by bitpshr** [comment]
All component themes have landed except for Calendar. There were some UX changes to the mock ups that required a decent amount of rework to the Calendar itself, and @smhigley and I have been tag teaming on these a bit.

Depending on @smhigley's availability, this should only have about 1 - 2 more days of work, including review.
