### ISSUE TITLE
Foundational Widgets

### ISSUE THREAD

**Issue by dylans** [dojo/widgets#23]
@kitsonk commented on [Tue May 17 2016](https://github.com/dojo/widget-core/issues/2)

This issue is to discuss what widgets should be part of the foundational widgets, potentially located in this package, or in related packages, as we begin to develop the "out of the box" widgets.

Currently we have.  Many of these were just created to be able to try to prototype and solve problems that other widgets may need and might be questionable in the final set:
- Button - Analog of `<button>`
- Container - Simply "owns" other widgets
- Dijit - A wrapper class for Dojo 1 Dijits
- LayoutContainer - Does a level of layout on contained widgets
- List - A simple list UI component
- Panel - A simple container
- ResizePanel - Provides a handle that allows one of the contained widgets to be resized
- TabbedPanel - All children owned are displayed as tabs
- TextInput - Analog of `<input type="text">`
- Widget - A generic "dumb" widget the includes all the foundational widget functionality and can render a tag and some content.

---

@mwistrand commented on [Mon Jun 27 2016](https://github.com/dojo/widget-core/issues/2#issuecomment-228785651)

Something comparable to `dijit/popup` whose sole purpose is to manage z-indices currently in use could also be very useful (essential?).

---

@dylans commented on [Mon Jun 27 2016](https://github.com/dojo/widget-core/issues/2#issuecomment-228787613)

A fair number of our clients like to extend dijit/Toolbar or other Menu components to create things like Ribbon bars or other UIs to contain various tabs/buttons/other commands. It would probably overlap with a fair amount of functionality from Panel/ResizePanel/TabbedPanel.

---

@dylans commented on [Thu Jun 30 2016](https://github.com/dojo/widget-core/issues/2#issuecomment-229755378)

Dojo 2 text inputs should support masking of input based on data format/constraints and should support i18n for that as well

---

@dylans commented on [Sun Jul 03 2016](https://github.com/dojo/widget-core/issues/2#issuecomment-230148869)

Does not belong in the core widgets repo, but a few of our big users rely heavily on the rich text editor. Either need a modern version of dijit/Editor, or need to wrap something else such as Trix which takes a vdom approach to RTE. A key feature is doing a decent job when pasting from Word.

---

@dylans commented on [Fri Sep 30 2016](https://github.com/dojo/widget-core/issues/2#issuecomment-250793514)

Some thoughts on validation patterns and other things that are commonly found in widget systems:
- invalid
- incomplete
- masking
- constraints
- localized (e.g. validated within a user's locale)
- display of state to users

---

@kitsonk commented on [Tue Oct 04 2016](https://github.com/dojo/widget-core/issues/2#issuecomment-251508506)

When appropriate we should turn this into an Epic and create the separate issues to track progress.

---

@agubler commented on [Thu Feb 02 2017](https://github.com/dojo/widget-core/issues/2#issuecomment-276920730)

@dylans do we think this should be moved to [widgets](https://github.com/dojo/widgets)?

---

@dylans commented on [Thu Feb 02 2017](https://github.com/dojo/widget-core/issues/2#issuecomment-276934204)

@agubler yes, the challenge is that ZenHub doesn't currently support moving epics from what I can tell, so I hadn't gotten around to re-creating the ticket yet. #85 should also be moved.

**Comment by kitsonk** [comment]
There are two outstanding widgets in progress.  These issues can stand on their own.  Closing.
