### ISSUE TITLE
Create Icon Widget

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#235]
**Enhancement** 

Previously it was though that stackable themes would solve the icon issue but when using them this way it was noted that we had to add aria tags etc... to aid accessibility. We should therefore wrap this up with an icon widget.

Widget to provide

- accessibility tags
- icon name autocompletion
- themeability

related issue: #54

**Comment by tomdye** [comment]
Work already completed on `Select` and `ComboBox` should be changed to use the icon widget.

**Comment by sebilasse** [comment]
@tomdye FYI attached a preview of the semantic ui widgets to https://github.com/dojo/widget-core/issues/559 - it also contains an Icon Widget.
While JSON Schemas and Autocompletion is not done yet, you can also find the Font Awesome Icon Names in /lib/SUIicons.ts

**Comment by eheasley** [comment]
This task was deemed to longer be necessary.
