### ISSUE TITLE
Button Layout in TabPane

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#239]
**Enhancement**

The button layout in TabPane is a bit challenging in certain use cases.  The buttons lay out at a fixed width and there isn't much space in the dojo theme and they get easily clipped.  As well when you have more rows than width, the multi-line gets very confusing visually.

<img width="396" alt="example" src="https://user-images.githubusercontent.com/1282577/27208078-55628418-51f8-11e7-9dd5-4628e7a4c94a.png">

**Comment by smhigley** [comment]
Closed with theme PR
