### ISSUE TITLE
List of widgets

### ISSUE THREAD

**Issue by dylans** [dojo/widgets#24]
@kitsonk commented on [Tue Nov 01 2016](https://github.com/dojo/widget-core/issues/85)

We need to specify a list of tentative foundational widgets, so we can whittle them down and figure out the priority order to build them.  We should create a table in the following format:

|Class Name|Description|Type|Sub Widget Classes|
|---|---|---|---|
|*ClassName*|*A simple description of the widget*|*Simple/Composite/Container*|*Sub or Child Widget Classes*|

---

@bitpshr commented on [Sat Dec 17 2016](https://github.com/dojo/widget-core/issues/85#issuecomment-261308029)

### Form Components
|Class Name|Description|
|---|---|
|Form*|Form component allowing for easy getting and setting of child component values|
|Select|Drop down component with optional support for multiple selection|
|Button|Button component with optional support for icons|
|ComboBox|Combination of a drop down component and a text input|
|DateBox|Combination of a calendar drop down component and a text input|
|TextInput*|Text-based input supporting email, number, password, tel, url, and custom patterns|
|RadioButton*|Styled radio button component|
|CheckBox*|Styled checkbox component|
|FileInput*|Styled component supporting regular and drag and drop file uploads|
|Slider|Component allowing for in-range value selection by moving a slider up or down|

_* Makes use of corresponding HTML element_

### Layout Components
|Class Name|Description|
|---|---|
|TabbedPanel|Tab-controlled container component|
|AccordionPanel|Collapsable container component|
|SlidePanel|Container component that can slide in and out of window|

### Misc. Components
|Class Name|Description|
|---|---|
|Dialog|Closable, optionally modal window that displays information or other components|
|Menu|Collapsable list of action items that can each be disabled|
|Tooltip|Label that appears on hover of another component|
|Header|Responsive horizontal toolbar that can show logo, menus, or action items|
|Progress|Component displaying percentage completion|

---

@smhigley commented on [Sun Dec 18 2016](https://github.com/dojo/widget-core/issues/85#issuecomment-267843748)

I like it! I would just propose a couple very minor changes:

- Button and Slider could use the corresponding native `<button>` and `<input type="range">` elements
- FileInput probably won't be able to use a styled HTML element alone if we want drag and drop functionality
- I think Select should be split into a native single-select dropdown and a separate multi-select component. WebAIM recommends against using the native multi-select box for accessibility, so we could use checkboxes under the hood to achieve the same functionality.

---

@dylans commented on [Tue Dec 20 2016](https://github.com/dojo/widget-core/issues/85#issuecomment-268391666)

Other suggestions (summarized from another thread):

* User resizable panel/region (e.g. like that found in https://user.sitepen.com/~kkelly/app-example/_build/src/ )
* Dialog should also be modeless in addition to modal (e.g. FloatingPane from Dojo 1)
* Should probably decouple DatePicker/icon/dropdown so users can show in various states)
* Slider horizontal and vertical?
* Switch (e.g. on/off found on mobile)
* Constraints on DatePicker
* TimePicker ?
* Menu on desktop vs. mobile will probably behave quite differently... may also want the hamburger style menu on desktop)

@smhigley The HTML5 slider doesn't give much in the way of CSS styling, or does it?

Also agree that FileInput via HTML DnD is important.

---

@smhigley commented on [Tue Dec 20 2016](https://github.com/dojo/widget-core/issues/85#issuecomment-268394398)

@dylans See http://codepen.io/smhigley/pen/ObWbdy for CSS styling examples with the native range input. It's also possible to switch horizontal/vertical with CSS.

---

@dylans commented on [Tue Dec 20 2016](https://github.com/dojo/widget-core/issues/85#issuecomment-268395846)

> @dylans See http://codepen.io/smhigley/pen/ObWbdy for CSS styling examples with the native range input. It's also possible to switch horizontal/vertical with CSS.

👍 nice!

**Comment by dylans** [comment]
FileInput is a surprisingly popular widget from dojox (in Dojo 1) given recent support and community issues. The Dojo 1 implementation has two versions, one done with Flash and the other with HTML5. Obviously we do not want to go the Flash route. There are two main use cases:

* Multi-file upload without having to select one file at a time
* Drag-n-drop files to upload (which we see implemented all over the week, e.g. Google Drive/Docs, Dropbox, etc.)

We might also consider integrating something third party like dropzone ( http://www.dropzonejs.com/ , https://github.com/enyo/dropzone , though it doesn't look to be particularly actively maintained), or at least surveying the other options out there.

**Comment by rishson** [comment]
@dylans I've added dependencies and tentative ordering to the widgets doc. Happy to track here also.

**Comment by kitsonk** [comment]
Our first set of widgets have been completed and outstanding issues are there for everything.  No value in holding this issue open.
