### ISSUE TITLE
Alignment of diffProperties/assignProperties

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widgets#247]
When working with the `shallowPropertyComparisonMixin` and trying to make the `assignProperties` more performant by removing the `deepAssign`, it quickly became apparent that the diff/assign functions are intrinsically linked - you have to perform the same iterations you do in the `diff` as you would do in the `assign`. This really means we would be best combining these to one function. To do this we are going to need return something with an interface along the lines of:

```typescript
interface PropertiesChangeRecord {
    changedKeys: string[];
    properties: WidgetProperties;
}
```

To bikeshed would be, what to call this new function that combines the 2.

**Comment by agubler** [comment]
Couple of potential names for the new combined property lifecycle function

- `applyProperties` - Not overly keen as they don't actually get applied to anything here
- `processProperties` - A bit generic but they are being processed, the process is diff and assign.

Thoughts on other suitable names? Avoiding the `diffAndAssignProperties` style.
