### ISSUE TITLE
Registry and stateFrom

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#25]
Considering we now have the registry provider interface, should widgets support either a reference to observe their state or a ID to be resolved via the registry provider?  This would further "delegate" responsibility to the application factory.  Therefore options would look something like this:

```typescript
type StatefulOptions<S extends State> = {
    state: S;
} || {
    id: string;
    stateFrom: ObservableState<S>;
} || {
    id: string;
    stateFrom: string;
    registryProvider: RegistryProvider<any>;
}
```

**Comment by novemberborn** [comment]
The app factory supports this when you load a widget definition. I suppose that logic could be duplicated in here, or even moved. I'm not sure if the loss in type checking is worth it though.

With the app factory that's to be expected, but it might be good if the other packages provide strong type checking guarantees.

**Comment by kitsonk** [comment]
Closing, will re-open if needed.
