### ISSUE TITLE
Consider layout mechanisms

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#250]
We need to consider what layout mechanisms we want to support in Dojo 2.
We should consider `css-grid` support, `flexbox` support etc.
We need to decide if we recommend 3rd party grid solutions, write our own, provide advice only...

**Comment by matt-gadd** [comment]
@rishson I think this issue should be moved to `dojo/meta`.

**Comment by bitpshr** [comment]
Thinking out loud, all our widgets are still rendered as DOM. Users can always write their own CSS to lay widgets out however they want. What would Dojo 2 provide as a framework to facilitate this? We should probably avoid anything resembling `dojo/layout`.

**Comment by rishson** [comment]
Issue moved to [dojo/meta #138](https://github.com/dojo/meta/issues/138) via [**ZenHub**](https://www.zenhub.com/)
