### ISSUE TITLE
Add fixed classes to `slider` to allow input styles to be themed

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#255]
**Enhancement** 

Currently you cannot easily theme the slider without having to replicate a large number of the structural styles. For instance if you wish to remove the `outline` on the input you must either use an `input` selector which goes against the css-modules guidelines or re-implement all of the base `.input` class styles.

**Comment by eheasley** [comment]
We confirmed this was fixed with our latest theme updates.
