### ISSUE TITLE
createMemoryStore#patch() should put() if ID is not in store

### ISSUE THREAD

**Issue by novemberborn** [dojo/widgets#26]
Patching the memory store fails if the ID isn't already in the store: <https://github.com/dojo/widgets/blob/fbe4369cd9386674fb593bbee7ad83c70aa5b766/src/util/createMemoryStore.ts#L292>.

This makes the following use case unnecessarily annoying:

```js
const store = createMemoryStore();

createWidget({
  id: 'foo',
  stateFrom: store,
  state: {
    bar: 'baz'
  }
});
```

This fails silently unless:

```js
const store = createMemoryStore({
  data: [
    { id: 'foo' }
  ]
});
```

Presumably we could just create the store entry?

**Comment by kitsonk** [comment]
Argeed...
