### ISSUE TITLE
Race conditions between setting initial state and rendering

### ISSUE THREAD

**Issue by novemberborn** [dojo/widgets#27]
When creating widgets with the `state` option, the initial state is set asynchronously:
- https://github.com/dojo/compose/blob/8c6016cea7becf1f6cd6f4f3da3b90eb45e2c972/src/mixins/createStateful.ts#L213 sets the state
- https://github.com/dojo/compose/blob/8c6016cea7becf1f6cd6f4f3da3b90eb45e2c972/src/mixins/createStateful.ts#L168 patches the observable
- which is an asynchronous operation https://github.com/dojo/widgets/blob/fbe4369cd9386674fb593bbee7ad83c70aa5b766/src/util/createMemoryStore.ts#L296

If Maquette renders before the state has propagated we may see errors. I suppose this depends on the interplay between the various micro-tasks and animation frames, as well as how these are polyfilled in older browsers.

It's not entirely clear to me why the memory store has to be asynchronous like this.

**Comment by kitsonk** [comment]
> It's not entirely clear to me why the memory store has to be asynchronous like this.

The main reason was to have consistent APIs, so that moving from one store that is async only to one the could be either does not cause an API change.  This has also highlighted the need to deal with a race condition, which if we had migrated to a wholly async store would have only become apparent then.  So we need to deal with the race condition.

One could be to put logic in the CachedRenderMixin to gracefully deal with the state not being present.  That seems like the most logical to me.

**Comment by vansimke** [comment]
I've dug into this for a while and I'm not sure that I understand the issue. From what I can tell, there are two ways that a widget's state can be updated:
1. [Synchronously](https://github.com/dojo/compose/blob/master/src/mixins/createStateful.ts#L192) and,
1. [Asynchronously](https://github.com/dojo/compose/blob/master/src/mixins/createStateful.ts#L189)

While I agree that setting the initial state asynchronously could cause issues, it doesn't appear to be possible. [this](https://github.com/dojo/compose/blob/8c6016cea7becf1f6cd6f4f3da3b90eb45e2c972/src/mixins/createStateful.ts#L213) line calls the setState method with the initial state of the widget and will always be synchronous. If the state changes after it is created, then it will execute down the path of being an ["observed state"](https://github.com/dojo/compose/blob/master/src/mixins/createStateful.ts#L242), but by that time the widget will already have been rendered and should be invalidated and re-rendered with no issues. 

@novemberborn can you comment on this and help me see what I'm missing?

**Comment by kitsonk** [comment]
This is strongly related to dojo/compose#54 and the related solutions to detecting when `state` is ready.

The refactoring of the widgets seems to be largely dealing with these situations, in that we are creating renders that work, with our without state and when the state is initialized it will cause the appropriate render.

So I am going to close this for now, unless we find a specific use case where we need to revisit this.
