### ISSUE TITLE
Adding Content to a Widget outside of Text

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#272]
**User Story**

As a developer, I may need to add and style non-text content to a widget with said content being just for display purposes, not affecting the function or behaviour of the widget.

**Specific Use Case**

I want to add a _save_ icon to a button, which is supplied from a FontAwesome stylesheet.

**Specific Use Case**

Using the `@dojo/widget` ComboBox, I want to change the down arrow to a plus sign.

**Comment by bitpshr** [comment]
The current story around this type of component modification isn't great. If a component doesn't explicitly expose a particular piece of its inner content as a property, a consumer can only reliably modify that piece of content through direct component extension. New patterns like offloading most heavy-lifting from the main `render` method to small helper `render` methods (#316) will make this type of direct extension easier to swallow across the board.

There's also the possibility of making much better use of the `registry` available in each component, but this approach is limiting. For example, unless the ComboBox's down arrow is contained within a child component (and not just raw vdom), there wouldn't be any actual component available to stub out using the registry.

I'm not sure there's anything actionable from this discussion beyond #316.

Action items:
* Close this ticket
