### ISSUE TITLE
Creating new Themes

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#276]
**User Story**

As a developer, I need to create a new theme for a set of widgets.  This set of widgets includes `@dojo/widgets` plus additional widgets from our custom widget library.

* I expect to be able to scaffold out all the appropriate files to create a theme for my given set of widgets.
* I expect to be able to validate that I have the appropriate themes for my widgets.
* I expect to be able to include my theme in my build and have it automatically available in the run-time environment.

**Comment by bitpshr** [comment]
We have no tooling that provides this much-needed functionality. I feel like this would make the most sense as part of the CLI.

Action items:
* Create a ticket against the CLI (or meta?) to implement this functionality
* Close this ticket
