### ISSUE TITLE
Architecture of CSS Modules

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#278]
**Discussion**

Our current CSS Modules, both for the structural _fixed_ styles, but also the design of the themes, do not promote modularization and reuse.  We should consider revisiting the overall _design_ of our CSS Modules, find common styles that should be used across the `@dojo/widgets` to create something that better leverages the ability of modules of CSS.

**Comment by tomdye** [comment]
I believe that this issue, as per the meeting we had previously, is concerning re-usable parts of our widget styles, both within `@dojo/widgets` and the possibilities for third party widgets.
Being able to extract the common aspects of our styles for textbox / select / combobox etc into a shared module as we do for `icons.m.css` is one of the goals we are aiming for.

**Comment by bitpshr** [comment]
Better modularity and reusability across the styles of some of our most complex components is being tracked at #312. Beyond refactoring heavily-shared code, I'm not sure how we can better facilitate CSS modularity apart from staying vigilant as our component library grows.

Action items:
* Close this ticket
