### ISSUE TITLE
Themed icon classes missing from built components

### ISSUE THREAD

**Issue by bitpshr** [dojo/widgets#295]
**Bug**

When using production-built components that use icon CSS classes, like Select, ComboBox, or TimePicker, the icon classes are applied incorrectly.

Package Version: latest

**Code**

1. `dojo create app --name test-app`
2. `cd test-app && npm install --save-dev @dojo/widgets`
3. Import and use Select, ComboBox, or TimePicker inside `widgets/HelloWorld`
4. Notice down arrow style errors

**Expected behavior:**

<img width="331" alt="screen shot 2017-09-06 at 11 24 21 am" src="https://user-images.githubusercontent.com/334586/30120130-fd230a40-92f5-11e7-891e-b196d007a012.png">

**Actual behavior:**

<img width="369" alt="screen shot 2017-09-06 at 11 23 26 am" src="https://user-images.githubusercontent.com/334586/30120125-f778844e-92f5-11e7-86d7-9de94711abd2.png">

**Comment by tomdye** [comment]
This has been fixed via a change to version `0.1.1` of `cli-build-webpack`, `cli-create-app` should be updated accordingly
