### ISSUE TITLE
Reconsider `main.ts`

### ISSUE THREAD

**Issue by bitpshr** [dojo/widgets#296]
**Bug**

It's odd that we don't provide a single CSS file that contains all component CSS files, but we do provide a single module that exposes all component modules. It's also weird that the module we provide only exposes top-level components, like TabController, but not necessary enums, like `Mode` from `CheckBox`. This means that even though I can use `CheckBox` from the `main` module, I still need to explicitly import supporting enums from respective component packages.

Package Version: latest

**Expected behavior:**

If we make it so `main.ts` provides all components, supporting components, and enums, we should also provide a `main.css` again. Otherwise we should remove `main.ts` altogether since it's an anti-pattern.

**Actual behavior:**

`main.ts` provides top-level components and no supporting classes or enums, and we don't provide a CSS file that includes all component CSS files.

**Comment by kitsonk** [comment]
We just need to consider if there is anything people would expect when consuming this module and having the `package.json` point at an _index_ module (or an AMD loader).  If the answer is nothing then so be it.
