### ISSUE TITLE
OptionData should live in Select instead of SelectOption

### ISSUE THREAD

**Issue by bitpshr** [dojo/widgets#297]
**Enhancement**

It would be nice if `OptionData` lived in `Select` since I only need to import `SelectOption` if I'm customizing an option using the registry, which isn't common. It's tedious to always have to import `OptionData` from `SelectOption`, especially since it's essential to the functionality of `Select`.

Package Version: latest

**Expected behavior:**

```ts
import Select, { OptionData } from '@dojo/widgets/select/Select';
```

**Actual behavior:**

```ts
import { OptionData } from '@dojo/widgets/select/SelectOption';
import Select from '@dojo/widgets/select/Select';
```

**Comment by smhigley** [comment]
OptionData is removed in #312
