### ISSUE TITLE
Dropdown styles missing from built ComboBox, Select, TimePicker

### ISSUE THREAD

**Issue by bitpshr** [dojo/widgets#299]
**Bug**

When using built components, the ComboBox and TimePicker have issues with the dojo theme.

Package Version: latest

**Code**

1. `dojo create app --name test-app`
2. `cd test-app && npm install --save-dev @dojo/widgets`
3. Import and use ComboBox, Select, or TimePicker inside `widgets/HelloWorld`
4. Notice dropdown style errors

**Expected behavior:**

<img width="324" alt="screen shot 2017-09-06 at 11 41 02 am" src="https://user-images.githubusercontent.com/334586/30120976-5ae5bb1c-92f8-11e7-9dec-f1a04961a37e.png">

**Actual behavior:**

<img width="361" alt="screen shot 2017-09-06 at 11 41 18 am" src="https://user-images.githubusercontent.com/334586/30120986-5e4fbf46-92f8-11e7-8e23-2d1ad22b0567.png">

**Comment by tomdye** [comment]
This will be fixed as part of #295

**Comment by tomdye** [comment]
This should now be fixed along with the release of `cli-build-webpack@0.2.0`
