### ISSUE TITLE
Specify classes and styles in options

### ISSUE THREAD

**Issue by novemberborn** [dojo/widgets#30]
`CachedRenderMixin` supports `classes` and `styles` setters on instances, and configuration via the store. It'd be useful if these could also be configured via the creation options. This would enable <https://github.com/dojo/app/issues/20>.

IMO the priority order should be options, mixins and then state. Once initialized, setters would try to update the state even if the value did not originally come from there. (Whether this behavior is correct probably merits a separate discussion, there are similar issues with the data visualization code.)

**Comment by agubler** [comment]
Given the following widget, you'd expect the final widget to have both the `options-class` and the `state-class`? Would you expect the `options-class` to be added to the `state.classes`, I think that it should be.

```js
const cachedRender = createCachedRenderMixin({
    listeners: { click },
    state: { id: 'foo', classes: [ 'state-class' ] },
    classes: [ 'options-class' ]
});
```

Performing a `cachedRender.classes = ['set-class']` will completely overwrite the `state.classes` by using the `cachedRender.setState({...})`

**Comment by novemberborn** [comment]
The tricky bit is what happens when you restore a previous application state. I'm now thinking that should take precedence over any initialization options. That's one of the things that emerged out of the app discussions: <https://github.com/dojo/app/pull/37>.

Then the order becomes:

* state, if `classes` is present
* options
* mixins

If state itself is available, then assigning `classes` should update that state. Perhaps this should be skipped when initializing.

**Comment by novemberborn** [comment]
I imagine that there might be `state`, but `'classes' in state` may be `false`. If it's not then `state.classes` should be used, even if it's an empty array.

**Comment by agubler** [comment]
That could work, if the `state.classes` is `false` then use the `options` otherwise ignore them

**Comment by novemberborn** [comment]
To recap, given an initializer `initialize(instance, options)`:

1. use `instance.state.classes` if `'classes' in instance.state`
2. use `options.classes` if `'classes' in options`
3. use `instance.classes`

**Comment by agubler** [comment]
@novemberborn yup I think that covers the scenarios that we were discussing.

**Comment by rishson** [comment]
@novemberborn @agubler if this is being worked on, can whoever if doing the work assign themselves please?

**Comment by agubler** [comment]
@rishson this is not currently being worked on by me.

**Comment by kitsonk** [comment]
This is related to #47 and subsumed by #46... so I think we should close this now and any thoughts should be added to #46.
