### ISSUE TITLE
Consider moving all widget files under individual widget folders

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#31]
At the moment, we split the `tests` and `src` into separate trees.
Should we change the layout to be:

widgets/dialog/Dialog.ts
widgets/dialog/tests
widgets/dialog/example

so everything is in one place?

[edited to remove `src` dir]

**Comment by rishson** [comment]
Also, if we publish a flat uber package, then we could also consider:

renaming `widgets/dialog/Dialog.ts` to `widgets/dialog/index.ts`

so the import can be `import Dialog from '@dojo/widgets/dialog'`, rather than `import Dialog from '@dojo/widgets/dialog/Dialog'`

**Comment by msssk** [comment]
> `import Dialog from '@dojo/widgets/dialog'`

Will this play well with loaders? I've seen a project that is unpleasant to use because its modules use package-style imports for local modules. This requires the loader configuration to specify a "package" for every single module loaded this way.

**Comment by dylans** [comment]
> Will this play well with loaders? I've seen a project that is unpleasant to use because its modules use package-style imports for local modules. This requires the loader configuration to specify a "package" for every single module loaded this way.

Yes, because we're not currently expecting people to actually load ESM in their app, but transpile to UMD and/or build using webpack.

**Comment by msssk** [comment]
What about during development?

**Comment by dylans** [comment]
During development you're not loading an ESM either, the only thing that is really using ESM is your editor/IDE to give autocomplete/intellisense. Everything gets transpiled, e.g. by using the watch command. Any widgets you install via npm will have .ts, .js, source maps, and d.ts, etc.

**Comment by jjrv** [comment]
When TypeScript is configured to emit SystemJS, at least `atom-typescript` will transpile on save without needing any watch task. I've made a tool called [cbuild](https://github.com/charto/cbuild) which autogenerates the necessary config, so an import from `@dojo/widgets/dialog` will get directed to `@dojo/widgets/dialog/index.js` if the former is actually a directory. It just needs to be run when new files are imported that were not used before.

**Comment by rishson** [comment]
Closing the discussion.
The migration to a single folder per widget can be tracker on #47 
For the uber package structure, we will go with `widgets/dialog/Dialog.ts`.
