### ISSUE TITLE
Design showcase page

### ISSUE THREAD

**Issue by bitpshr** [dojo/widgets#330]
**Enhancement**

Our showcase page at https://dojo.github.io/widgets/ is pretty ugly. It would be great to get a mock up that we can implement to make it look nicer.

Package Version: latest

**Comment by kitsonk** [comment]
We also discussed with @agubler and @matt-gadd that we should consider moving it to `dojo/examples` as well?

**Comment by kitsonk** [comment]
Issue moved to [dojo/examples #247](https://github.com/dojo/examples/issues/247) via [**ZenHub**](https://www.zenhub.com/)
