### ISSUE TITLE
Organize z-index values

### ISSUE THREAD

**Issue by smhigley** [dojo/widgets#335]
**Bug**

We already have some issues with conflicting z-index values (see https://dojo.github.io/widgets, and try opening the SlidePane or Dialog over the TitlePane). We should document and implement a standard approach to z-index values, and probably put it in the widgets readme and perhaps also in an article or tutorial.

Initial thoughts on z-index ranges:

0 - 100: Any specific component layering (e.g. social icons that overlap an image)
100 - 200: Tooltips
200 - 300: Dropdowns (e.g. menu or combobox)
300 - 400: Fixed position elements
400 - 500: Modals / Dialogs (including underlays)
500 - 600: Notifications and special cases

**Comment by kitsonk** [comment]
There should be a design and standards for widgets... it can start off as a wiki page, but could be added to the "docs" section of dojo.io as a recommended set of conventions for creating widgets.

**Comment by smhigley** [comment]
@kitsonk The PR is almost ready. I'm drafting words for the widgets readme right now. I agree, it should go somewhere on dojo.io too 👍
