### ISSUE TITLE
Convert all relevant components to use meta

### ISSUE THREAD

**Issue by bitpshr** [dojo/widgets#339]
**Enhancement**

This issue is to remind us to convert all components to use applicable meta functionality. Many components existed before any meta implementation existed in widget-core, and we should be sure to keep our component base as up-to-date as possible.

**Comment by kitsonk** [comment]
We should itemise any widgets as part of this ticket.

**Comment by agubler** [comment]
I believe all areas that should use an existing meta have been converted the remaining few included in #437
