### ISSUE TITLE
Triage existing components for a11y best practices

### ISSUE THREAD

**Issue by bitpshr** [dojo/widgets#342]
**Enhancement**

We've been doing a good enough job at preserving good a11y practices (thanks largely to @smhigley.) We can do better though. Some components, like AccordionPane and TitlePane, don't support arrow key navigation. We should use this (large) issue to go through each component and add a11y as necessary, especially since this is a pillar of Dojo 2 widgets.

Package Version: latest

**Comment by tomdye** [comment]
Looks like this has been done as all related tasks are completed
