### ISSUE TITLE
Tab widget: Understand when tab contents have finished loading

### ISSUE THREAD

**Issue by umaar** [dojo/widgets#349]
**Enhancement** 

Enhance the tab widget to expose an event when the tab contents have loaded.

Reasons:

1) It might be useful in general for consumers of a tab widget
2) It would be useful for me in a test where tab content is loaded in an async manner, but without knowing when the async tab contents have finished loading, it's hard to know when to make render assertion.

**Comment by tomdye** [comment]
I don't think that it's the concern of the tab widget itself to provide such a callback. Any event / callback would come from the store / data provider? The tab itself should be a pure view component displaying content via the property it has been provided.

**Comment by bitpshr** [comment]
For reference, we have an example of asynchronously-loaded tab content on the example page. As Tom mentioned, we intentionally decided to keep data loading responsibilities outside the scope of the TabController itself. Instead, you set the `activeIndex` to the desired tab and set the `loading` property to `true`. Whenever any content-loading operation finishes, whatever that may be, you simply set the `loading` property to `false`:

```ts
w(TabController, {
	// ...
	onRequestTabChange: (index: number, key: string) => {
		this.setState({
			activeIndex: index,
			loading: true
		});
		refresh = refreshData().then(() => {
			this.setState({ loading: false });
		});
	}
})
```

Leaving data-loading responsibilities up to a parent (and ultimately and application store) will be a common pattern in Dojo 2 components.

**Comment by morrinene** [comment]
We don't have any action items here, so closing this out.
