### ISSUE TITLE
Radio / Check buttons have no background color

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#352]
**Bug ** 

Radio and Check buttons have no background color, so the color they are placed on bleeds through, this may be intentional.

![screenshot 2017-11-01 17 24 03](https://user-images.githubusercontent.com/814453/32287747-9fe59338-bf29-11e7-8743-ab5fe23fa356.png)

**Comment by tomdye** [comment]
@smhigley @bitpshr thoughts please?

**Comment by smhigley** [comment]
It was intentional on my part, but I don't have strong opinions either way. I'd defer to Scott on his preference

**Comment by tomdye** [comment]
Looks like we're setting a background colour for the toggle and for the thumb on the slider, so I guess I'd expect these to follow suit?

**Comment by smhigley** [comment]
It would help protect contrast, so there's that. Toggle and the slider thumb seem a little more separate from the page background to me, but that's pretty subjective. Again, I don't care much either way :)

**Comment by tomdye** [comment]
for clarity i'm only talking about the radio button itself, not the label

**Comment by smhigley** [comment]
I figured, since I'd have to question your sanity if you were talking about the label 😆. For this one, I'm fine going ahead and making the background white. I think tabs should have a look from Scott though, since it's a more prominent difference.

**Comment by bitpshr** [comment]
As a downstream user, I wouldn't expect to have to style the background color of my input to use it on a non-white BG. +1 for a background color.

**Comment by smhigley** [comment]
Background color added in #358
