### ISSUE TITLE
Down chevrons on select / combobox are different

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#354]
**Bug** 

![screenshot 2017-11-01 17 27 33](https://user-images.githubusercontent.com/814453/32287856-0203ca8a-bf2a-11e7-8492-d84ea489e81b.png)

I would expect `Select` to be the same as the others

**Comment by pottedmeat** [comment]
These are the same characters using the same style rule but with different font sizes.

**Comment by pottedmeat** [comment]
The arrows used by Select and ComboBox look basically identical but have different CSS names, structure, etc. Could be worth standardizing.
