### ISSUE TITLE
Investigate normalising Label usage

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#360]
@tomdye commented on [Mon Nov 06 2017](https://github.com/dojo/widget-core/issues/749)

# Enhancement

Currently when using a `Label` it is set as the outer node of a widget and is passed classes by the creating widget to enable theming and styling. We should investigate using an outer div instead to avoid needing to pass classes and other such fields to the label.

Plan is to investigate different approaches considering the pros and cons including passing classes vs properties and utilising `for` / `id` properties to allow accessibility. 

## Current
```ts
const rootClasses = [
   css.root,
  disabled ? css.disabled : null
];

w('Label', { extraClasses: { root: rootClasses.join('') }, labelText: 'Email Address' }, [
	v('input', { type: 'text' })
]);
```

## Proposed 1
```ts
v('div', { classes: this.theme(css.root) }, [
	w('Label', { for: 'inputId', labelText: 'Email Address', disabled: true }),
	v('input', { id: 'inputId', type: 'text' })
]);
```

## Proposed 2
```ts
v('div', { classes: this.theme(css.root) }, [
	w('Label', { labelText: 'Email Address', disabled: true }, [
		v('input', { type: 'text' })
	])	
]);
```

**Comment by tomdye** [comment]
The downside of proposed solution 1 is that we need to look at how we manage `before` / `after` labels as it would be down to each widget to decide where to put the label? But I guess that a simple `children.reverse()` can be used when `labelAfter` or similar is set to `true`.

The plus side of 1 however as @bitpshr touches upon is the predictable dom output.

**Comment by tomdye** [comment]
https://github.com/dojo/widgets/blob/master/src/textinput/TextInput.ts#L156-L167 is a perfect example of the unpredictable dom output and css property passing we currently have.

**Comment by smhigley** [comment]
I have a couple requests for the PR for this:

- Deal with how to handle before/after labels (as you mentioned), ideally without separately offloading it to the 9 or so widgets that currently use Label.
- Use Checkbox as a test case, since it has two different label stylings, one for a normal checkbox/radio (where the text is to the right of the input), and one for the toggle button (text above or below, as is common for other form widgets).

I'm excited to see what this will look like :)

**Comment by bitpshr** [comment]
I agree with @smhigley about testing with our most "difficult" label-using widget and finding a way to deal with label placement in a DRY manner. Adding a property like @tomdye suggested doesn't seem horrible; we already offload duplicated functionality to each of our ~9 form components, so one more wouldn't be a deal breaker for me. This approach would definitely add fuel to the `FormMixin` fire, too, which is a good thing in my opinion. We have many form components that work, and I feel like we're finally at a point where we have the knowledge to optimize duplicated functionality pretty easily.

Another thought I keep going back to is that our form components shouldn't include label functionality at all. If I use a TextInput, why couldn't I just put a Label before or after it, just if I were using HTML elements? Is built-in `label` property functionality only for styling purposes? Is it only so we can reference the underlying input without using an `id` and `for`?
