### ISSUE TITLE
Use string enum values as CSS keys

### ISSUE THREAD

**Issue by bitpshr** [dojo/widgets#365]
**Enhancement**

Some of our components (SlidePane, Tooltip) use enums with string values. These values are then used as keys to access CSS classes on the CSS module object. Unfortunately, because of Microsoft/TypeScript#13042, we can't properly type these use cases yet. A fix for this issue is slated for 2.7 and we should update our components at that time.

Package Version: latest

**Expected behavior:**

```ts
const enum Align {
	bottom = 'bottom',
	left = 'left',
	right = 'right',
	top = 'top'
};

const alignCss: {[Key in Align]: string} = css;
```
**Actual behavior:**

```ts
const enum Align {
	bottom = 'bottom',
	left = 'left',
	right = 'right',
	top = 'top'
};

const alignCss: {[key: string]: any} = css;
```

**Comment by estaub** [comment]
> A fix for this issue is slated for 2.7

Now 2.8, it seems; see Microsoft/TypeScript#13042.

**Comment by msssk** [comment]
This appears to no longer be an issue - SlidePane is using a union type of string literals, and other modules using `enum` appear to have strong typing in place (instead of just `[key: string]`).

**Comment by tomdye** [comment]
This can now be closed
