### ISSUE TITLE
TextInput on widget-core 0.2.0 validation broken on IE11

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#367]
**Bug**

The validation of a TextInput on `widget-core@0.2.0` does not properly apply styles on IE11 (works on all other browsers).

**Expected**

![validated-working](https://user-images.githubusercontent.com/1282577/32519408-9498496e-c404-11e7-978a-b1bb34806ce9.gif)

**Actual**

![validated](https://user-images.githubusercontent.com/1282577/32519419-9a1c79b4-c404-11e7-9996-c5a459ea6d0e.gif)

**Comment by agubler** [comment]
This is a bug in `widget-core`, IE11 doesn't support adding and removing multiple classes like `element.classList.add('a', 'b')` or `element.classList.remove('a', 'b')`.

Have raised https://github.com/dojo/widget-core/pull/756 that should resolve the issues.
