### ISSUE TITLE
Specifications for widgets

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#37]
Hi all.
Going forward, I think we need much clearer intentions when creating widgets. What I'd like to propose is:

1) each widget 'spec' is a separate issue (and PR)
2) spec lists features needed for initial version, and things excluded for now

What I'd like to do, is create initial issues for all in-flight widgets and have a standard set of features that either do or do not need to be completed, e.g.

[Template spec](https://github.com/dojo/widgets/wiki/Widget-specification-template) is now on the wiki for this repo.

**Comment by rishson** [comment]
@smhigley @tomdye @bitpshr comments appreciated so we can resolve asap.
Once we have agreement, I'll create widget spec issues for everything in-flight.

**Comment by bitpshr** [comment]
This sounds fine to me. I have a few verbiage nitpicks (components don't emit events, they call a function property) but this conveys the right ideas.

**Comment by rishson** [comment]
@bitpshr ta - updated.

**Comment by rishson** [comment]
- what responsive design features are needed

**Comment by rishson** [comment]
We now have a basic specification that we agree on.
I'll leave this open so we have an issue that you can copy the spec details from, until we have a suitable other location for this information.

**Comment by rishson** [comment]
Closing as the widget spec is now on the `widget` repo wiki.
