### ISSUE TITLE
Widget themability check

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#401]
**Enhancement** 

We should take time to check how themeable the widgets we have created really are.
A popular style of web components that people often like to use is `material`. A good way to test the themeabilty of our components would be to have a go at creating a material theme.

**Comment by dylans** [comment]
Rather than doing material at this time, why don't we go through this process and create a Dojo 1 flat theme for Dojo 2's widgets ( see comments at https://github.com/dojo/examples/issues/275 )... this will improve interop with Dojo 1 and also verify that this is working as it should.

**Comment by tomdye** [comment]
I think the reason for Material was that it is a little more complicated that the dojo 1 flat theme and thus a better test of the theming system. I understand your point though.

**Comment by tomdye** [comment]
This is covered in the material epic https://github.com/dojo/widgets/issues/615
