### ISSUE TITLE
Slider `<output>` receives focus in Edge

### ISSUE THREAD

**Issue by mwistrand** [dojo/widgets#402]
**Bug** 

When navigating with the `tab` key through an application that contains the `Slider` widget on MS Edge, the `<output>` tag receives focus. As far as I can tell, this is unexpected behavior, but it still causes focus to appear to vanish. It would be preferable if this element were explicitly excluded from receiving focus.

Package Version: rc

**Expected behavior:**

The slider's `<output>` cannot receive focus through keyboard navigation.

**Actual behavior:**

The slider's `<output>` can and does receive focus through keyboard navigation.

**Comment by rorticus** [comment]
PR, https://github.com/dojo/widgets/pull/476

**Comment by agubler** [comment]
Fixed by #476
