### ISSUE TITLE
Select: question about design

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#409]
**Enhancement**

Currently to have an option selected in a `Select` the end user _must_ specify the `getOptionSelected` property.  This seems excessive for most use cases where the `value === selectedOption`.  Doesn't it make sense to have default logic that if there is no `getOptionSelected` specified that it defaults to the selected option === value?

**Comment by smhigley** [comment]
I like that idea. Originally it lacked a default because an option can be anything, not just a string. I tried adding something of a double fallback, where it uses `getOptionValue` if present, and if not falls back to just `option`.
