### ISSUE TITLE
Text Input Widget

### ISSUE THREAD

**Issue by smhigley** [dojo/widgets#41]
**Enhancement** 
Related to #5 

Features:
- Includes styles for disabled, required, valid, and invalid states
- accepts callback functions for `onInput`, `onChange`, `onFocus`, and `onBlur`
- value is controlled by the parent component (example included)

Future changes:
- Could use better styles for certain states, a "wait" state, and perhaps icons

**Comment by tomdye** [comment]
I think there are events missing from this list. Need to consider those supported by dojo 1 dijits.
