### ISSUE TITLE
Non-Leaky Virtual DOM Abstraction

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#43]
While we don't have any plans to migrate from Maquette, one of our main goals was to abstract users of widgets largely from the VDOM implementation.  That also led us to choose Maquette which generates DOM based on HyperScript, a popular alternative to JSX.

We should therefore re-export the HyperScript implementation in dojo-widgets (along with appropriate virtual DOM interfaces) and depend upon those re-exports so that if, for whatever reason, we wanted/needed to swap out implementations, the impact would be minimal.

**Comment by matt-gadd** [comment]
This is fixed as part of `d`
