### ISSUE TITLE
cursor:pointer on radio and checkbox elements?

### ISSUE THREAD

**Issue by dylans** [dojo/widgets#434]
Should we specify `cursor:pointer` for the active areas on checkbox and radio elements?

**Comment by smhigley** [comment]
It's not the default cursor style, so I'd be slightly inclined against it. I'm not too opinionated either way, though.

**Comment by smhigley** [comment]
There's some debate about this (see https://blog.marvelapp.com/buttons-shouldnt-hand-cursor/ vs. https://twitter.com/heydonworks/status/974328229937938433). On balance, in the absence of user testing, I think our defaults should respect browser defaults.
