### ISSUE TITLE
Closed Titlepane contents shows through the title

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#449]
**Bug** 

Due to the nature of the `margin-top` animation for hiding a titlepane's contents, it is visible through the titlepane itself. The contents appears to be at a level above that of the title and thus, it is clickable. This can render the title toggle itself to be unusable.

![screenshot 2018-02-02 14 36 01](https://user-images.githubusercontent.com/814453/35738318-69111c24-0826-11e8-8f2f-941703f4934c.png)

**Comment by smhigley** [comment]
Merged in #450: resizing can cause the contents to overlap the title.

**Comment by tomdye** [comment]
I do not think this is related to resizing, it is due to the z-index / absolute positioning of the parent / child and the titlepane not having a background color.
