### ISSUE TITLE
Closed titlepane contents shows on page resize

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#450]
**Bug** 

When a page / split pane is resized that contains a closed titlepane, it's contents when being re-flowed can show out form underneath the title.

This is likely due to the the nature of the `margin-top` used rather than `height: 0` to hide the contents.

![screenshot 2018-02-02 14 38 20](https://user-images.githubusercontent.com/814453/35738416-b9cec38c-0826-11e8-86c9-1a5090388ad4.png)

**Comment by smhigley** [comment]
Merging with #449, as this appears to have the same underlying cause
