### ISSUE TITLE
No DatePicker Widget

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#452]
**Enhancement** 

Dojo 1.x had a date picker component. We seem to be missing this from dojo 2. We have a calendar, but not an input that triggers it.

**Comment by krezovic** [comment]
I'm also in need of this widget, and it is sadly not ready yet. It would be even more amazing if it supported constraints (min/max selectable date) like the Dojo1 widget did.

**Comment by agubler** [comment]
We could create a `DatePicker` using the `Calendar` widget, if it had properties for the min and max date, @smhigley do you think this is something sensible that we could add?

**Comment by schontz** [comment]
I've got something in the works for min/max dates for the `Calendar` widget as well as a `DatePicker` input widget that uses the `Calendar`. There are some issues around `focus` that I am trying to solve for the `DatePicker` before it can be properly tested.

**Comment by xiaohulu** [comment]
should support input time, for example `2018-01-01 1:00`

**Comment by jellison** [comment]
Superseded by Issue #941. Should we close this one?

**Comment by tomdye** [comment]
Can now be closed as date picker is merged and will be released in version 7
