### ISSUE TITLE
Calendar back / forward tabs are not included in it's size calculation

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#453]
**Bug** 

The back / forward buttons to either size of the calendar as not included in it's size calculation and as such they render off screen when the widget is placed in a restrictive space.

![screenshot 2018-02-02 14 42 29](https://user-images.githubusercontent.com/814453/35738709-8e48af7e-0827-11e8-8928-60dda5ccecda.png)

**Comment by smhigley** [comment]
Fixed with theme PR
