### ISSUE TITLE
Checkbox / Toggle widgets should be split

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#455]
**Enhancement** 

The checkbox and toggle widgets should likely be split into their own widgets.
The css file for these would be made much simpler and it will be clearer to users how to use and style them.

**Comment by smhigley** [comment]
Now that widget properties are extendable, this should be simple 👍

**Comment by sebilasse** [comment]
just my two cents :

> The css file for these would be made much simpler and it will be clearer to users how to use and style them.

This is more a general issue with themed classes which can be `null` –
in my personal widgets I give it a "counter-class" even if it is an empty css definition, here :
`mode === Mode.toggle ? css.toggleWrapper : css.inputWrapper`

**Comment by tomdye** [comment]
This work has been documented in the material checkbox issue by @pottedmeat
