### ISSUE TITLE
Inconsistency of radio / check / toggle / input layout

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#457]
**Enhancement** 

- Checkboxes are inline
- Radios are inline
- Toggles are block
- Inputs are block
- Selects are block
- Buttons are inline

We should be consistent between inline / block elements. All form elements should likely be `inline`.

![screenshot 2018-02-02 14 53 49](https://user-images.githubusercontent.com/814453/35739238-e3b933ec-0828-11e8-98bb-e68f41519963.png)

**Comment by itorrey** [comment]
The toggle should be inline but we should remove the option of having an on / off text.
