### ISSUE TITLE
Hover effect of enhanced text box does not include before / after addons

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#458]
**Bug** 

The onHover shadow / highlight on the text input does not extend to the addons. This makes them look like they are not a single input.

![screenshot 2018-02-02 14 54 37](https://user-images.githubusercontent.com/814453/35739330-28e9b66c-0829-11e8-87ad-7d0772a5a7d6.png)

**Comment by smhigley** [comment]
Other libraries that include input addons don't appear to include the addon in the hover/focus styles (e.g. https://getbootstrap.com/docs/4.0/components/input-group/). Might be good to get Scott's opinon.

Either way, I've updated form widgets to always append a `.focused` class to the root node so more advanced focus styles are at least possible, even if we don't decide to implement them.

**Comment by tomdye** [comment]
I agree that bootstrap does not include the add-on in it's focus ring, but it's the drop shadow that I found most troubling. It made it look like it was not part of the same component.

**Comment by smhigley** [comment]
I've actually forgotten what was in the original comp, but either way I was planning to send this (and a couple others ) to Scott for his opinion when he has availability.
