### ISSUE TITLE
Clicking on an enhanced text input addon does not focus the input

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#459]
**Bug** 

I would expect the text input to be focused when the addon is clicked.

**Comment by smhigley** [comment]
I actually don't think clicking on an addon should focus the input, as they aren't buttons or interactive elements. While there aren't any official pattern guidelines (that I know of) directly addressing this, other libraries don't appear to focus the input when clicking on an addon (e.g. https://getbootstrap.com/docs/4.0/components/input-group/)

**Comment by smhigley** [comment]
Going to close this now -- I actually think it's pretty important that interacting with non-interactive elements should not do anything.
