### ISSUE TITLE
Styles and Classes on Widgets

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#46]
There are two main types of styles and classes that need to be dealt with when rendering a widget:

* Those bound to the class/factory
* Those that are instance based

There actually should be no class bound styles, as any styles that are provided on render should be calculated from the `instance.state` and not from the class.

Therefore to facilitate this, we need to do the following:

* Remove `.styles` from widget interfaces
* Make `.classes` a `readonly string[]` with a static value of the merged array of string using the merge array feature of `dojo/compose` (see: dojo/compose#46)
* Change the default render logic to use the `.classes` property as a base and mixin any classes provided in `instance.state.classes`.

Then when creating a class or mixin, the developer would just supply any class bound classes to be mixed in as a `string[]` in the prototype.

**Comment by kitsonk** [comment]
Refs #45 in that what we need to do here will essentially effect that as well as #35 to a minor degree.

**Comment by novemberborn** [comment]
Following up from <https://github.com/dojo/app/issues/20> (via https://github.com/dojo/widgets/issues/30), should it be possible to specify `classes` at instantiation time *without* specifying them in the state?

I suppose these too could be considered "static" and added after getting the widget classes. Then any dynamic stuff needs to come from the state.

**Comment by agubler** [comment]
`classes` and `styles` have been removed as options for widgets and the only way to specify classes outside of statically in the widget is via `state`, so in answer I don't think so.

**Comment by novemberborn** [comment]
@agubler that makes <https://github.com/dojo/app/issues/20> really hard to implement. I wonder if it should be possible to provide `state` that isn't actually stored anywhere? Otherwise App will have to create IDs for all widgets it instantiates, and might just have to require a default widget store.

I'm actually bringing this up since I'm looking to simplify the `dataviz` behavior around this kind of config. Sounds like the idea is that you can specify defaults on the class level, and allow customization via state. So I'll try to make that work.

**Comment by novemberborn** [comment]
> I wonder if it should be possible to provide state that isn't actually stored anywhere?

[Turns out it is](https://github.com/dojo/compose/blob/7ffe6c5b50d3dd0ad4cf6df2d34bc441eaeee165/src/mixins/createStateful.ts#L239:L250), yay!

**Comment by kitsonk** [comment]
> Turns out it is, yay!

The only caveat/edge case that I don't think we have handled is that if `.observeState()` after creation, the "local" state will be patched with the observed state, which might result in some surprises.  We could change it that the first thing it does when observing state is that it takes any local state and patches that before it starts observing.  I suspect that is all a bit of an edge case though.

**Comment by novemberborn** [comment]
> The only caveat/edge case that I don't think we have handled is that if .observeState() after creation, the "local" state will be patched with the observed state, which might result in some surprises. We could change it that the first thing it does when observing state is that it takes any local state and patches that before it starts observing. I suspect that is all a bit of an edge case though.

Would be good to avoid surprises like this.
