### ISSUE TITLE
Enabled and Disabled checkboxes look exactly the same

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#461]
**Bug** 

Spot the difference:

![screenshot 2018-02-02 15 04 23](https://user-images.githubusercontent.com/814453/35739704-5e4e7206-082a-11e8-96b1-cc0bed270fec.png)

**Comment by smhigley** [comment]
Closing, this is an issue with implementation of the disabled checkbox within showcase, not with disabled styles themselves. The current styles are below:
<img width="328" alt="screen shot 2018-02-07 at 2 16 11 pm" src="https://user-images.githubusercontent.com/3819570/35944516-8a8bb8f2-0c11-11e8-8abd-dd0425e010fd.png">
