### ISSUE TITLE
Rendering and Rendering Children Nodes

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#47]
In working with `todo-mvc` it has highlighted that the rendering `.getChildrenNode()` is not as downstream functional as might be.  It is simply getting overridden, even when there are mixins that are trying to provide a generic method.  It means that in a lot of final widget cases, the mixins aren't "helping".

The `nodeAttributes` functionality in #40 does feel like that is an improvement, where now the VNode attributes can be easily expressed and mixed into the final widget without just taking a hammer to `.getNodeAttributes`.  In fact, no downstream developer would now need to touch `.getNodeAttributes`.

Also it was discussed with several of us offline that ideally, no downstream developer would actually want to touch `.render()` when creating a custom widget.  While it is semantically most logical extension point, the widget system provides more functionality, like intelligent caching and translating parts of state into the rendered virtual Node, that end developers should really only be expressing their "additive" functionality in a final widget class.

This topic is for discussing this thinking and making any proposals to how we might improve this.

**Comment by kitsonk** [comment]
This is going to be addressed by the new implementation of the base classes for widgets.

**Comment by agubler** [comment]
This has been addressed with the implementation of `createWidgetBase` and `d`
