### ISSUE TITLE
Add onSelect/onClear callbacks to ComboBox

### ISSUE THREAD

**Issue by krezovic** [dojo/widgets#485]
**Enhancement**

Please add onResultSelect callback to the ComboBox widget, and pass the raw value to it (similar to the getResultLabel). This makes easier to distinguish from filter text and selected value, especially when value  isn't raw text but an object.

Please add onClear callback/event so there's a distinction from input and clear (not that important).

**Comment by krezovic** [comment]
Even better: Replace onChange call with onResultSelect call in _selectIndex.

**Comment by smhigley** [comment]
Assuming we do this, I think `onResultSelect` should fire before `onChange` (and with a direct reference to the result value, as @krezovic suggested).

**Comment by krezovic** [comment]
humble ping?

**Comment by smhigley** [comment]
@krezovic I think we'll leave out `onClear`, since I don't see a use case for that vs. highlighting and deleting text. We're adding `onResultSelect`, though.

Thanks for checking in!
