### ISSUE TITLE
Document controlled form components

### ISSUE THREAD

**Issue by dylans** [dojo/widgets#49]
From #38:

> For beta we will have a form widget that works with controlled components only.
> We will document this restriction.
> At a later date, we will raise an issue on widget-core for a way to handle uncontrolled components also.

This ticket is to add relevant documentation to the readme.

**Comment by rishson** [comment]
Decided to pull the section on this from the README.
The form tutorial should include a section on `controlled vs uncontrolled` form widgets.
@smhigley are you currently writing the form tutorial?

**Comment by dylans** [comment]
@rishson either @vansimke or I will be writing the content for the form tutorial.

**Comment by kitsonk** [comment]
Closing in favour of dojo/dojo.io#136
