### ISSUE TITLE
Add Intern configuration for supported browser matrix

### ISSUE THREAD

**Issue by devpaul** [dojo/widgets#490]
PR #488 has removed the ability to run tests against multiple browsers. We should add intern configurations that allow developers to run tests against browserstack and saucelabs from their machine against multiple browsers. i.e. 

```json
"configs": {
	"browserstack-all": {
		"extends": "browserstack",
		"environments": [
			{ "browserName": "internet explorer", "version": "11" },
			{ "browserName": "chrome", "os": "Windows", "os_version": "10" }
			{ "browserName": "edge" },
			{ "browserName": "firefox", "os": "Windows", "os_version": "10" },
			{ "browserName": "safari", "version": "9.1", "platform": "MAC" },
			{ "browserName": "iPhone", "version": "9.1" }
 		]
	}
}
```

We should also update the README to describe usage and optionally update `grunt test` to allow selecting a configuration.

**Comment by rorticus** [comment]
It looks like these were added back in https://github.com/rorticus/widgets/commit/b0d26dc521ecf393bcb5a430412ed4e0b3ed82a3 so this is probably a non-issue?

**Comment by rorticus** [comment]
Chatted with @devpaul and we agreed we can close this as the grunt commands have been added back.
