### ISSUE TITLE
Read only and disabled ComboBox are indistinguishable

### ISSUE THREAD

**Issue by krezovic** [dojo/widgets#528]
**Bug** 

Package Version: 0.6.1

There seems to be little difference between passing readOnly and disabled attributes to ComboBox. The rendered widget has no visible difference. I'd expect that buttons are dropped when readOnly is passed and that the value is shown in the input field.

**Comment by tomdye** [comment]
This is more likely an issue with the default dojo theme rather than widgets themselves, we will look at fixing this as part of the improvements we are doing to support material theme

**Comment by tomdye** [comment]
closing this as we are removing combobox
