### ISSUE TITLE
Slider: Themed `.outputTooltip` class missing

### ISSUE THREAD

**Issue by sebilasse** [dojo/widgets#533]
**Bug**

Currently a slider's `.outputTooltip` can't be themed because only the fixed class is applied.

Package Version: latest

**Code**
```
return v('output', {
  classes: [ this.theme(css.output), outputIsTooltip ? fixedCss.outputTooltip : null ],
  // ...
```

could be

```
return v('output', {
  classes: [
    this.theme(css.output),
    outputIsTooltip ? this.theme(css.outputTooltip) : null,
    outputIsTooltip ? fixedCss.outputTooltip : null
  ],
// ...
```

**Comment by smhigley** [comment]
Good catch:  I believe this styling should be moved entirely to the theme, as the position should be themeable, and the current styles provide little value in a fixed class.
