### ISSUE TITLE
Start week from Monday in the Calendar?

### ISSUE THREAD

**Issue by krezovic** [dojo/widgets#539]
**Enhancement**
 
Package Version: git master

In the current calendar implementation, the week starts from Sunday. Is it possible to change it so it starts from Monday? It seems to be tied to JS Date() functionality.

I've noticed that you can change the order of week days by specifying the desired order in your translations array passed as "weekdayNames" property. Is it possible to use this fact somehow?

**Comment by dylans** [comment]
I would add to this that it should also be possible to get this information from the i18n package for the current locale.

**Comment by karlhp** [comment]
@dylans, the first weekday may not match the locale for multi-lingual users. I use for example all software in English but German formatting rules for numbers and dates. I think there should be always an option to set the first weekday and other formatting features independent from the locale.
