### ISSUE TITLE
Consistent typings for multiple possible string values

### ISSUE THREAD

**Issue by sebilasse** [dojo/widgets#555]
**Enhancement**

E.g. 
1) `Button` has a **Type** like `export type ButtonType = 'submit' | 'reset' | 'button' | 'menu';`
Advantage: It does not need to be imported to be consumed (although it is exported here probably for "explicit" consuming).
Disadvantage: It can't be used for runtime checks.

2) `Checkbox` has an **Enum** 
```Typescript
export enum Mode {
    normal = 'normal',
    toggle = 'toggle'
}
```
but it is used so that it needs to be imported when consumed
```Typescript
export interface CheckboxProperties /* ... */ {
    mode?: Mode;
    /* ... */   
}
```
Advantage: Can be used for runtime checks.
Disadvantage: Must be imported for consumers.

My personal solution is:

Use Enum everywhere but like
```Typescript
export interface CheckboxProperties /* ... */ {
    mode?: Mode | keyof typeof Mode;
    /* ... */   
}
```
Advantage: Can be used for runtime checks and does not need to be imported because TS can do string comparison now.
Disadvantage: ?

**Comment by tomdye** [comment]
@sebilasse We will look at making these consistent as a part of the changes we are making to widgets to support a material theme.
