### ISSUE TITLE
How to use dojo 2 widgets as web components in a non-Dojo application

### ISSUE THREAD

**Issue by ngjaying** [dojo/widgets#556]
**Question** 

Dojo.io: "Dojo provides first class support for web components." 
I understand the cli tool to export custom widgets based on Dojo to web component and use it. But I don't know how to use the Dojo own widgets like dojo-button as web component.

Package Version: 2.0.0

**Code**

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Test dojo widget web components</title>
    <script src="https://unpkg.com/@webcomponents/webcomponentsjs@next/webcomponents-loader.js"></script>
    <script type="module" src="../../node_modules/@dojo/widgets/button/index.mjs"></script>
  </head>
  <body>
    <dojo-button>Hello dojo</dojo-button>
  </body>
</html>
```

**Expected behavior:**

Show the button as expected

**Actual behavior:**

In Chrome, an error in console:

> Uncaught TypeError: Failed to resolve module specifier "tslib". Relative references must start with either "/", "./", or "../".

No button is rendered, only the text "Hello dojo" is rendered.

**Comment by matt-gadd** [comment]
Hi @ngjaying. You have to use the Custom Element builds from `@dojo/widgets` which are located in the `dist` directory. You will also want to load a theme from `@dojo/themes`. Here's an example of using the dojo widgets button:

https://codesandbox.io/s/3v41rklro5

Hope that helps!

**Comment by matt-gadd** [comment]
I have also raised an issue to improve the documentation on this here: https://github.com/dojo/widgets/issues/557

**Comment by ngjaying** [comment]
@matt-gadd Thank you, it works well.
