### ISSUE TITLE
Make Icon widget extendible so it can support more FontAwesome icons

### ISSUE THREAD

**Issue by schontz** [dojo/widgets#558]
**Enhancement** 

Right now dojo only supports 23 of the FontAwesome icons. If you try and use an icon that is not specified in the theme CSS you get an error. You cannot extend `IconType` or even extend `IconBase` to include more types.

**Comment by schontz** [comment]
Currently, dojo only imports those 23 icons into the font that it uses for icons. For many cases this is sufficient. But since `IconProperties.type` is set via the CSS classes provided there is no way to add more icons.

You *should* be able to extend `Icon` for your use and add another CSS file with another font and set of icon definitions. But that doesn't work because the new set will never satisfy the `IconProperties` type requirement.

**Comment by tomdye** [comment]
@schontz the reason for the `Icon` widget was to abstract away the underlying fontawesome usage and to add in `a11y` tags etc whilst providing a way to theme the icons we use within our widgets. If you want to use the complete font-awesome offering then the best approach would be write your own `FontAwesomeIcon` widget for your app or simply use `v` to create an `i` element with the appropriate font awesome class names used. I do not think this is something we will be doing within our widget offering right now.
