### ISSUE TITLE
Include non DoJo-widgets

### ISSUE THREAD

**Issue by ILoveITScience** [dojo/widgets#567]
Hi guys,

the DoJo components are fine but there are a lot of components missing. Is there an example or documentation how to include third party libraries to a DoJo2 project? Are there any special libraries that should be preferred (like Material UI)?

Thanks

**Comment by tomdye** [comment]
@ILoveITScience we are currently working on incorporating material design into our widgets offering as well as working on adding more widgets to the library. You can use the dojo/interop package if you want to import and use dojo 1 dijits within your app. Please feel free to reopen and comment on this issue if you need more information.
