### ISSUE TITLE
Potential Grid Enhancements/Fixes

### ISSUE THREAD

**Issue by agubler** [dojo/widgets#576]
**Enhancement**

 * Customisable column widths?
 * Configurable row height?
 * Reset column sort?
 * Show error and retry for failed cell update? (configurable?)
 * Indicate the a cell is editable?
 * width/height currently controlled by enclosing widget, is that the best way?
 * stock cell renderers, such as combo box, action etc?
 * Add/delete row from grid?
 * Refresh grid?
 * Footer overhaul, make it configurable?
 * Drag and drop column order?
 * Resize column?
 * Don't allow cell edit if no updater provided (even if column configured as editable?)?

**Comment by smhigley** [comment]
Update:

- Indicate the a cell is editable
Editable cells now include a themeable edit button (it is hidden and conditionally shown on focus in the current base styles + dojo theme)

- width/height currently controlled by enclosing widget, is that the best way
Width is still controlled by the grid's parent, but height is now set directly in the grid properties

**Comment by odoe** [comment]
It would be useful to add some interactivity to the Grid. Right now it can display data just fine, but there are many cases where getting the selected row would be very helpful.

Looking at Grid, it could look something like this on the `Row` that is passed down from the `Grid`.

```
export interface RowProperties {
	id: number;
	item: { [index: string]: any };
	columnConfig: ColumnConfig[];
  updater: (rowNumber: number, columnId: string, value: any) => void;
  // optional handler
  onSelectHandler?: ({ id, [index: string]: any }) => void;
}

return v(
  'div',
  {
    // add handler
    onClick: () => {
      if (onSelectHandler) {
        onSelectHandler({ id, item });
        // probably toggle a local state property
        // for selected state too
      }
    },
    classes: [this.theme(css.root), fixedCss.rootFixed],
    role: 'row',
    'aria-rowindex': `${id + 1}`
  },
  columns
);
```

This could also open up the the opportunity to support multi-select at some point as well.

**Comment by agubler** [comment]
Update: 

 * Resize column - using the column configuration option `resizable` allows columns to be resized.

**Comment by nikkabi** [comment]
Adjust page size, via properties?

**Comment by agubler** [comment]
A lot of these have been implemented in the current grid, this grid will be gradually replaced by a new "resource" based grid.
