### ISSUE TITLE
Dialog animations are hard coded and cannot be changed using theming.

### ISSUE THREAD

**Issue by evra** [dojo/widgets#578]
**Enhancement**

Dialog animations classes are hardcoded and cannot be changed using theming. It would be helpfull to have a class in the dialog.m.css to change default animations.

Package Version: 3.0.0

**Comment by agubler** [comment]
@evra It looks like `enterAnimation` and the `exitAnimation` are part of the Dialog's [properties API](https://github.com/dojo/widgets/blob/master/src/dialog/index.ts#L31).

```ts
w(Dialog, { enterAnimation: css.animation })
```

**Comment by evra** [comment]
@agubler thank you for pointing out, but this requires me to set this for each call of the dialog widget. It would be good to change the default animation in a theme.

**Comment by agubler** [comment]
@evra It would indeed require you to import the css and use it for every `Dialog` usage. 

An alternative would be to write a small wrapper around the `Dialog` that would allow you to include the `exit` and `enter` animations as part of a theme. 

```ts
import WidgetBase from '@dojo/framework/widget-core/WidgetBase';
import Themed, { theme } from '@dojo/framework/widget-core/mixins/Themed';
import { w } from '@dojo/framework/widget-core/d';
import Dialog, { DialogProperties } from '@dojo/widgets/dialog';

import * as css from './styles/CustomDialog.m.css';

@theme(css)
export class CustomDialog extends Themed(WidgetBase)<DialogProperties> {
	protected render() {
		return w(Dialog, {
			enterAnimation: this.theme(css.enter) || undefined,
			exitAnimation: this.theme(css.exit) || undefined,
			...this.properties
		});
	}
}
```

I created a repository with a [small example](https://github.com/agubler/dojo-custom-dialog) to demonstrate and [deployed it here if you wanted to take a look](https://dist-ekqyxzhbve.now.sh).

**Comment by evra** [comment]
@agubler thank you. It works for my case pretty well.
