### ISSUE TITLE
Widget design system

### ISSUE THREAD

**Issue by smhigley** [dojo/widgets#581]
## What parts of Material Design do we want to adopt as a guideline?
1. Visual styles, likely through `@dojo/themes` for the most part
2. Interaction and animation design
	- this isn’t entirely divorced from visual styles, e.g. in the case of floating labels
3. Functional specs, as defined under Behavior/Usage sections
	- Defined under Behavior/Usage, excluding animation-specific behavior
	- While there are certainly extra features our widgets could use, in general these are not too different from what we have implemented now.
	- Examples of behavior we do not implement include: toggle switch loading state, swiping between tabs, and optionally fixing tabs on scroll

## What is the story around creating and extending themes?
1. How do you extend a theme with different variables?
	- Example use case: a company with both dark and light themes, or a night mode toggle
	- Right now the only options are to drop IE11 support and override the CSS properties at a higher degree of specificity, or fork the theme
	- forking introduces the problem of needing to maintain both themes
2. How easy is it to theme composite widgets?
	- Does cli-create-theme now create all the included widgets’ stylesheets when selecting a composite widget to theme?
	- When creating a composite widget, it seems like a common use case to need some parent-widget-specific style variations on child widgets. Are we comfortable recommending `extraClasses` for this? Are there other options?

## How easy is it to extend existing widgets for behavior?
- Example: the ripple interaction effect
- If we don’t build all Material Design-specified behavior variations into each base widget, it should be easy to extend the widget to add it
- Right now, the render method has been broken up to be more easily overridable, but some of the broken-out functions still include private class methods

**Comment by tomdye** [comment]
Closing this as we have individual material issues and a larger material discussion issue here: https://github.com/dojo/widgets/issues/615
