### ISSUE TITLE
Release process for individual widgets

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#6]
**Enhancement**

As well as an uber release of `@dojo/widgets` we would like to have individual packages for each of the widgets such that they can be consumed on a more granular level.

For example a button could be published to `@dojo/widgetButton`. and later imported into a project via `import createButton from `@dojo/widgetButton/createButton`.

**Comment by rishson** [comment]
refs dojo/widget-core#283

**Comment by rishson** [comment]
No longer plan to do. This is not needed, given each widget is a separate module in the uber package and so production builds will only include the imported widgets.
