### ISSUE TITLE
Base Classes for Widgets

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#60]
### Motivation

We have started articulating the concepts around the encapsulation of widgets:
- **Simple Widgets** - These are the _atoms_ of widgets, in the sense that from the outside the encapsulate a single state and the rest of the application interacts with them as a single instance, which renders up virtual DOM node.
- **Composite Widgets** - For code reuse purposes, it maybe useful to create a widget out of _sub-widgets_.  Externally, composite widgets should not leak these internal instances.  The _sub-widget_ state should not leak into the application state, where likely the outer composite widget stores its state.  Externally, changes are made to the composite widget's state and internally the composite widget manages the state of the children without _assistance_ from outside.
- **Container Widgets** - These are widgets that contain/own child widgets, which are in turn containing widgets or single widgets.  Container Widgets should be able to handle _n_ number of child widgets.  They may or may not constrain the classes of children they manage.  The manage the children via an `OrderedMap` and by default render in the order they were added.

To provide more explanation of the above, the following are logical examples of widgets and how they fit the concepts above:
- A text box is a _single simple_ widget, in that it performs one function, to represent a single property of a business object (or application state).
- A drop down select box is a either a _simple_ or _composite_ widget, in that externally, we would want to interact with it where it renders represents a single property of a business object (or application state) and we wouldn't want to care about its implementation.  Realistically though, it would encapsulate the drop down button and the drop down list and the text box as separate widgets, of which the complex outer widget would manage.  The individual state of whether the drop down list is displayed or not, aren't material to the application state and therefore should be encapsulated inside the widget.
- A todo item is a _composite_ widget, in that again, it represents a single instance of a business object, but has several sub-widgets which allow the user to further interact and view the state of the business entity it is representing.  Again, though, externally, the state of the todo item is fully expressed in the state of the todo item widget, and the complex widget manages the state of the sub-widgets.
- A panel is a _container_ widget, in that it would take _n_ number of arbitrary number of widgets which it would layout.
- A tabbed panel, on the outside, would be a _map container_ widget which would have two labelled widgets, the tab bar, which would be a _list container_ of tab buttons and a panel container which would be a _list container_ of panels.
### Proposal

To that effect, we should have 3 base classes for widgets, which are then used to build all other widgets:
- **Widget** which would build on the _Stateful_ base class.
- The **d** function will be used to express composite _sub-widgets_ and **Widget** will be able to resolve and manage the return from the **d** function.
- **ContainerWidget** which would build on **Widget**.

Other features can then be added to these bases via mixins.

Edit: Refined widget types
Edit: Combined **ContainerListWidget** and **ContainerMapWidget**
Edit: Combined **CompositeWidget** and **Widget** and added **d** concept.

**Comment by kitsonk** [comment]
Further discussion as a group has re-worked some of this, which I will update, but also identified that we need to materialise these concepts better, which we need to break down into separate tasks, which I will also do in the near future.

**Comment by rishson** [comment]
Closing as all issues addressed and functionality is now implemented.
