### ISSUE TITLE
TabPane

### ISSUE THREAD

**Issue by bitpshr** [dojo/widgets#61]
**Enhancement**

Create a TabPane component.

Note that features such as showing tabs that don't fit within available real estate in a menu can be added at a later time.

### Specification

**Callback props**:
```ts
activeIndex?: number;
loadingIndex?: number;
tabs?: TabConfig[];
onRequestTabChange?(index: number): void;
onRequestTabClose?(tabs: TabConfig[]): void;
```

**Interaction**
- Clicking on a tab triggers `onRequestTabChange`
- Clicking on a tab close button triggers `onRequestTabClose`

**States**
_None._

**Value add**
A TabPane would solve the common UX issue of needing to show multiple sets of information as designated by the currently selected tab.

**Controlled or uncontrolled**
Controlled.

**Icons**
- Close Icon

**Responsive design**
None, until dictated by initial theme mockups from @itorrey.

**Comment by rishson** [comment]
@bitpshr I'm just filling out a spec for the Accordion, and just wondered about async filling of tabs/titlePanes.
Would we pass all the tabs (inc all content) to a tabPane or would we only pass content for the tab that has been selected, e.g.

```
//user selects 'tab 1'
onRequestTabChange(1); 
//optionally, show 'tab 1' in a wait state
//parent fetches content for 'tab 1', the sets content on child
w(TabPane, {tabContent: selectedTabContent}, []);
```
? (or similar - above is only pseuocode 😄 )

**Comment by bitpshr** [comment]
I added a `loadingIndex` property to the specification so we can support asynchronous tabs. I think passing all tabs all the time is a good idea; only one will ever be rendered at a given time and if the tabs weren't passed, the user would have to manage `activeIndex` and `activeContent`. It feels cleaner to only manage the index.

Something like this:

```ts
w(TabPane, {
	activeIndex: this.state.activeIndex,
	loadingIndex: this.state.loadingIndex,
	onRequestTabClose: newTabs => this.setState({ tabs: newTabs }),
	onRequestTabChange: index => {
		this.setState({ loadingIndex: index });
		someAsyncTask.then(() => this.setState({
			activeIndex: index,
			loadingIndex: null
		}));
	},
	tabs: <TabConfig[]> this.state.tabs || [{
		label: 'Default',
		content: v('div', [ 'abc' ])
	}, {
		label: 'Closeable',
		content: v('div', [ 'def' ]),
		closeable: true
	}]
});
```

**Comment by rishson** [comment]
So thinking about this some more, I'm still not convinced that you need the content for all the tabs to be passed to the `tabPane`. The argument for this design used to be that tab switching was quicker if the content for the tabs was already there in separate `divs` but only 1 div was visible at a time.
In a reactive architecture, it still feels cleaner to me, to just pass the content that you want to show.

For the async behaviour, if you have a child, lets say `expensiveWidget` that takes awhile to populate, then you could always construct this widget with no data (the widget will know what it's empty state looks like) and pass this widget in as the content to display, and re-render the `tabStrip` when the content for the `expensiveWidget` is available in the parent. This way, you separate out the fetching of data for `expensiveWidget` population and each widget is responsible for constructing its own empty and/or wait states.

**Comment by bitpshr** [comment]
Passing configurations for all tabs isn't necessary, but I really don't like the idea that users would have to manage their own array of children, a separate array of tab labels, and also an activeIndex. What's the benefit of only passing one at a time? There's no real reason not to pass all at once, even if some of the configurations are empty and require async loading when they're shown (see example above.) I'm also not a fan of every child of a tab pane having to explicitly handle an empty state. That forces a child widget to conform to behavior of the TabPane.

I really like just using an activeIndex and loadingIndex in that example.

**Comment by bitpshr** [comment]
I'm guessing passing only one at a time would look something like this:

```ts
let tabs: TabConfig[] = [{
	label: 'Default',
	content: v('div', [ 'abc' ])
}, {
	label: 'Closeable',
	content: v('div', [ 'def' ]),
	closeable: true
}];

let tabLabels = tabLabels: [{
	label: 'Default'
}, {
	label: 'Closeable'
}]

w(TabPane, {
	activeIndex: this.state.activeIndex,
	loadingIndex: this.state.loadingIndex,
	activeContent: this.tabs[this.state.activeIndex],
	onRequestTabClose: index => {
		let newTabs = tabs.slice();
		newTabs.splice(index, 1);
		tabs = newTabs;

		let newTabLabels = tabLabels.slice();
		newTabLabels.splice(index, 1);
		tabLabels = newTabLabels;
	},
	onRequestTabChange: index => {
		this.setState({ loadingIndex: index });
		someAsyncTask.then(() => this.setState({
			activeIndex: index,
			loadingIndex: null
		}));
	},
	tabLabels: tabLabels
});
```

Problems:
- Tab labels and tabs are managed independently, so the user has to be absolutely sure the order of each array is identical, otherwise mismatches between tab labels and tabs will occur. Also, when a closeable tab is closed, a user has to manually splice both arrays.
- A user has to pass `activeIndex` and `activeContent`, which seems weird and verbose.
- I still have to define an array of tabs, the difference now is that I have to manage it myself.

I don't see any benefit to this, and in fact, it seems more error prone.

**Comment by rishson** [comment]
So where I'm getting at with empty states is, each widget should know what it should look like with no data. Consider a reasonably complex widget such as a `contact` (displays picture of a person, their name, address, phone, rating and other misc info). I would expect, when building this widget, to specify that if no picture passed in props, then show placeholder outline image etc and create the  empty state. A different example may be a `recentProjects` list widget that when you pass no projects to it, shown placeholder text saying something like "Hey there. Our app works way better when you select projects 😄". I don't see how these design ideas tie either of these widgets to the behaviour of the `tabPane` - to me these are just empty state (like you find [here](http://emptystat.es/)
I guess if the empty states are cheap to create then there is little harm in passing all of the children to the `tabPane`, but if the child widgets get significantly complex, then I worry about performance on mobile.

**Comment by bitpshr** [comment]
Ignoring the empty state issue for now, what is the performance concern of passing all tab configurations to the TabPane vs. defining them outside of the parent render (see examples above)? In both approaches, the array is already created, it's just a matter of where it lives. Only one active tab is being rendered at any given time, too. I don't see how any browser would suffer from poorer performance.

**Comment by bitpshr** [comment]
As for the empty states, this ties tab widgets to TabPane behavior because if a widget is used inside a tab and _doesn't_ support a loading or wait state but is async, the user will be looking at an empty widget and not know what's going on. Why not just have the TabPane show a wait state instead? Even still, a user could not use `loadingIndex` if they don't want to, and things would work how you described (they'd set `activeIndex`, the TabPane would switch to their widget with no data in its own custom wait state, and they could re-render when their async operation completes.) So basically, using `loadingIndex` isn't mutually exclusive to your approach with wait states. We can support both.

**Comment by bitpshr** [comment]
@rishson I played with both designs this weekend and managing a conditional array of tab configurations outside of the component definition is really tedious. It feels like the component we're providing is incomplete. Since only one tab is being rendered at a given time and because `content` is optional when defining tabs, the method of defining all available tabs shouldn't incur any performance penalty. For example, a heavyweight tab could just not pass `content` if it's not active. The parent can do whatever it wants to optimize what's defined at runtime.
