### ISSUE TITLE
Grid: show and hide the search field

### ISSUE THREAD

**Issue by ILoveITScience** [dojo/widgets#613]
I would like to show and hide the filter search fields without reloading the data.

In an angular application I would set the a property in the corresponding css class to display:none to hide the search fields. But the css classes in DoJo are generated names like f6CI9pI0 text-input-mroot3EzSD. 

Important: I don't want  reload the data in the grid. (this would happen if I change the column configuration, right?)

If this feature is not available. Would you please provide it?

Current DoJo version: 4.0

**Comment by agubler** [comment]
@ILoveITScience I don't think that the grid will reload if you just pass an updated (new object) column configuration, have you tried doing something like this https://codesandbox.io/s/zr2kr075q4?

**Comment by ILoveITScience** [comment]
Thx, works fine
