### ISSUE TITLE
Grid: replace sorting button with custom picture

### ISSUE THREAD

**Issue by ILoveITScience** [dojo/widgets#625]
Hi, I want to change the sort button.  Instead the button I would like to use a custom image

Widget: Grid
DoJo Version: 4

![image](https://user-images.githubusercontent.com/17782816/48413085-e295df80-e746-11e8-82c0-78b2faa4f994.png)

**Comment by agubler** [comment]
@ILoveITScience Is it just the icon that you want to be able to style for the grid?

**Comment by ILoveITScience** [comment]
yes, I would like to get rid of the button and use custom icons.

**Comment by ILoveITScience** [comment]
Hi @agubler, whats the status of the issue?
