### ISSUE TITLE
Slider Widget

### ISSUE THREAD

**Issue by edhager** [dojo/widgets#626]
- mdc readme https://github.com/material-components/material-components-web/tree/master/packages/mdc-slider
- mdc docs https://material.io/develop/web/components/input-controls/sliders/
- mdc demo https://material-components.github.io/material-components-web-catalog/#/component/slider

![md slider](https://user-images.githubusercontent.com/4441986/48443392-d8271600-e745-11e8-999b-b529047cccd6.png)

## Overview

This issue is concerned with implementing a material themed slider component.

Like the material slider, this slider will not support a range (multi-thumb slider) but unlike material, this slider will support a vertical track mode.

## Changes to structure

Remove the `label` and `output` nodes.  Users can easily add `label` and `output` nodes to the vdom when and where needed and link them to the slider using the `for` and `id` attributes.     

The continuous material slider has a focus ring:
![MDC Continuous Slider States](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F15TSjP7vUkx3t8dP0CiA6lxg_gFQQ07zr%2Fsliders-continuousslider-states2.png)

The discrete material slider also has a pin icon that appears as the thumb is moved.
![MDC Discrete Slider States](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1MFWceSStOgPmqholFlYP9AE1PMEUUrqZ%2Fsliders-discreteslider-states2.png)

The current Dojo slider widget DOM structure:
![dojo-slider-dom](https://user-images.githubusercontent.com/4441986/48573544-5956e800-e8c1-11e8-9941-3c0fe4cfd3da.png)

To accommodate the focus ring, the discrete value pin icon and discrete value markers, update the DOM structure to be more like the material slider structure:

![mdc-slider-dom](https://user-images.githubusercontent.com/4441986/48576160-a4282e00-e8c8-11e8-8ba5-9c76c655fafc.png)

Create a container node for the track and one for the thumb.
 
## New properties

* `onValue(value: string) => void`: callback upon value change
* `showTickMarks(show: boolean) => void`: show tick marks when a step value is given 
* `enablePin: boolean`: when `true`, a pin icon (tooltip) will appear next to the thumb as the thumb is being moved.  

## Breaking changes

* will no longer call an `onChange` callback; will call `onValue` instead
* will no longer call `onkeyDown` and `onKeyPress`
* specific touch events have been removed
* will no longer call `output`
* will no longer support `outputIsTooltip` - replaced with `enablePin`

## Tasks

- [ ] Restructure and update props
- [ ] Implement theme and update dojo theme

**Comment by tomdye** [comment]
This has been done
