### ISSUE TITLE
Select Widget

### ISSUE THREAD

**Issue by rorticus** [dojo/widgets#634]
- mdc readme [https://github.com/material-components/material-components-web/tree/master/packages/mdc-select](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select)
- mdc docs [https://material.io/develop/web/components/input-controls/select-menus/](https://material.io/develop/web/components/input-controls/select-menus/)
- mdc demo [https://material-components.github.io/material-components-web-catalog/#/component/select](https://material-components.github.io/material-components-web-catalog/#/component/select)

## Overview

This issue is concerned with implementing a material themed select component. Most of changes to the `Select` widget relate to the way options are handled by the component. Currently, options are typed as `any` and other properties are required to decipher the options. Instead, `options` will be required to conform to an interface to make the options predictable.

## Changes to structure

- MDC select renders the arrow, then the select, then the label. Dojo native select renders the label, then the select, then the arrow. We may need to change the order of a few DOM elements.

## Breaking changes

- `options` will not take an array of  `any`, but instead an array of `SelectItem`.
- `getOptionDisabled` will be replaced with a `disabled` property on the item.
- `getOptionId` will be removed and replaced with the item's `value` property.
- `getOptionLabel` will be replaced with a  `label` property on the item.
- `getOptionText` will be replaced with a `text` property on the item.
- `getOptionValue` will be replaced with a `value` property on the item.
- remove `labelAfter` property
- possibly rename the `useNativeElement` option.

## Future work / properties

- `outlined: boolean` renders the select with an outline rather than with a line beneath it (this is a material property)

**Comment by tomdye** [comment]
@rorticus I believe you are right about the order of dom elements. Are there any concerns re. `a11y` of the select if we make those changes?

**Comment by rorticus** [comment]
WIP: https://github.com/rorticus/material-select

**Comment by rorticus** [comment]
I've got the basics of the enhanced select plumbed in,

![image](https://user-images.githubusercontent.com/2008858/51056559-2d9a6a80-15b1-11e9-9abe-fa175319278b.png)

I didn't realize that `Listbox` doesn't already include keyboard support, so it might be easier to redo that widget too...

**Comment by rorticus** [comment]
Added more styles, keyboard support, and a few other misc things. I think this is close and can probably start to be integrated back into widgets soon.

![2019-01-14 14 42 07](https://user-images.githubusercontent.com/2008858/51137049-f247a800-180b-11e9-933f-68eea6ddc83e.gif)

The changes to Listbox are non breaking (just some style imports). I wanted to keep it that way because otherwise everything that uses Listbox would have to change all at once.

There are a couple of focus styles that aren't being applied from material.

**Comment by tomdye** [comment]
New select has been implemented via https://github.com/dojo/widgets/pull/962. Material theme issue will be separate
