### ISSUE TITLE
Grid: 

### ISSUE THREAD

**Issue by saxn-paule** [dojo/widgets#636]
It would be great, if rows/columns/cells could have custom CSS classes. Is the only way to achieve this the use of a CustomRenderer?

As a general improvement an even/odd CSS class for rows would be very helpful.

Corresponds to: https://github.com/dojo/widgets/issues/576

**Comment by agubler** [comment]
@saxn-paule In the next release of @dojo/widgets (5.0.0), you should be able to control the classes applied to the grid in a couple of ways.

1) Either by writing a custom theme for the grid, which can be set globally or passed directly to the grid component with the `theme` property.
2) Add additional classes using the `classes` property on the grid which will apply the classes to the underlying widgets along side the existing theme.

```ts
const classes = {
	'@dojo/widgets/grid-row': {
		root: [ 'my-custom-stripe-class' ]
	}
};

w(Grid, { classes: classes });
```

```css
.my-custom-stripe-class:nth-child(even) {
	background-color: pink;
}
```

This would add the `my-custom-stripe-class` to the node(s) in `Row` that have the `root` class applied.

Hope this helps!

**Comment by saxn-paule** [comment]
Thank you very much for your reply.

Is there a timeline when v5.0.0 will be released?
