### ISSUE TITLE
a11y State

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#64]
@kitsonk commented on [Wed Nov 16 2016](https://github.com/dojo/widget-core/issues/109)

---

@agubler commented on [Fri Mar 10 2017](https://github.com/dojo/widget-core/issues/109#issuecomment-285629510)

Do we have any more information about what this entails? If there is an enhancement here, should it be in @dojo/widgets?

---

@kitsonk commented on [Fri Mar 10 2017](https://github.com/dojo/widget-core/issues/109#issuecomment-285651825)

Apologies.

Any widget should have defined when it uses [ARIA states](https://www.w3.org/TR/wai-aria/states_and_properties) to help make the widget more accessible and that the widget should have tests to ensure that the ARIA State matches the visual state of the widget throughout any lifecycle.

---

@agubler commented on [Fri Mar 10 2017](https://github.com/dojo/widget-core/issues/109#issuecomment-285651995)

@kitsonk should we move this widgets?

**Comment by rishson** [comment]
Can we we remove the beta blocker label please unless there is a defined issue to resolve. The way this is documented is more of a goal or aim, rather than a specific action that needs addressing in the next 5 days.

**Comment by kitsonk** [comment]
Sorry, I thought I was just copying over the label, but I realised you removed it 2 days ago from that issue.  There is work to do here.  I have no idea if dojo/widgets are properly using ARIA state, do you?

**Comment by bitpshr** [comment]
All the components so far except for SlidePane use ARIA attributes per the w3c recommendations. We definitely need to revisit them, though, as I don't think their usage is exhaustive at all.

**Comment by rishson** [comment]
I do! 😀 
The widgets in beta 1 meet our goal of: `a11y` compliant widgets out the box ™️ 
I also agree that it would be beneficial to do a sweep over them to see if we can improve, but don't believe this to be a blocker to initial release.

**Comment by eheasley** [comment]
What we have right now already passes the basic needs for accessibility so we have a good foundation in place.  Any improvements from this point would be iterative to fill specific needs.  We feel that there is nothing actionable left for this particular task.
