### ISSUE TITLE
Grid: trying to get data from REST-API, but seeing spinners

### ISSUE THREAD

**Issue by yduman** [dojo/widgets#643]
Hi!

I am fairly new to the Dojo Framework, so bare with me if my question might be too trivial. I really want to solve my problem now. I created a simple Express server, which returns me the same data which you can see in the examples folder.

In my Widget, I use the lifecycle method `onAttach` in order to fetch the data and store it into the field `gridData`, which I provide to `createFetcher`. Since I call `invalidate()` after getting my data, I am triggering a re-render afaik, so my data should be displayed, but all I see are just spinners. 

Maybe I am thinking a bit too React-ish, but unfortunately I can't find a proper solution via Google or GitHub Issues. The code looks like the following:

```tsx
@theme(css)
export class Home extends HomeBase<HomeProperties> {
  private gridData: any[];
  private columnConfig = []; // the same like in the examples

  async onAttach() {
    const res = await fetch("http://localhost:1234/data");
    this.gridData = await res.json();
    this.invalidate(); // trigger re-render
  }

  protected render(): DNode {
    return (
      <div>
        <Grid
          columnConfig={this.columnConfig}
          fetcher={createFetcher(this.gridData)}
          height={500}
        />
      </div>
    );
  }
}
```

**Comment by agubler** [comment]
Hi @yduman, thanks for the question!

The issue with is that the `Grid` will not re-render when the fetcher changes as functions are ignored by default in the property diff'ing process.

There are a couple of approaches that would work for this scenario:

1) Preferably you could create a custom fetcher, that deals with making the request to load the data and then manages the pagination requests from the grid based on the using the data. I've created an example in codesandbox https://codesandbox.io/s/8z6lnly8rj. It uses a custom `createRestFetcher` to manage the grid data (with sorting and filtering), this is something that we could look to add to the `@dojo/widgets/grid/utils` module. 

```ts
import { filterer, sorter } from "@dojo/widgets/grid/utils";
import { FetcherOptions } from "@dojo/widgets/grid/interfaces";

function createRestFetcher(url: string) {
  const fetchRequest = fetch(url, {
    headers: {
      "Content-Type": "application/json"
    }
  });
  let data: any[];
  return async (page: number, pageSize: number, options: FetcherOptions) => {
    if (!data) {
      const response = await fetchRequest;
      const json = await response.json();
      data = json.data;
    }

    const offset = (page - 1) * pageSize;
    const temp = sorter(filterer(data, options), options)

    return {
      data: temp.slice(offset, offset + pageSize),
      meta: { total: temp.length }
    };
  };
}
```

Usage:

```ts
<Grid
    columnConfig={this.columnConfig}
    fetcher={createRestFetcher('https://my-url')}
    height={500}
/> 
```

2) For it to work using the `onAttach` to load the data, you would need to add `fetcher` to the class and then create the fetcher one time in the `onAttach` method. Then conditionally render the grid based on whether the fetcher has been created (i.e. the data has been returned from the server).

```ts
export class MyWidget extends WidgetBase {
  private _fetcher: any;
  private columnConfig = []; // the same like in the examples

  async onAttach() {
    const res = await fetch("http://localhost:1234/data");
    const data = await res.json();
    this._fetcher = createFetcher(data);
    this.invalidate(); // trigger re-render
  }

  protected render(): DNode {
    return (
      <div>
        this._fetcher ? <Grid
          columnConfig={this.columnConfig}
          fetcher={this._fetcher}
          height={500}
        /> : null
      </div>
    );
  }
}
``` 

I hope this helps!

**Comment by yduman** [comment]
Thank you so much @agubler ! This helps a lot.

**Comment by yduman** [comment]
Hey,

sorry for opening this up again, but I also tried to use your approach without using TSX. So by just using the `v()` and `w()` functions. Suprisingly, the approach of handling the things inside of `onAttach` didn't work. I couldn't see any Grid. The other approach of writing a custom fetcher and provide it as a Grid prop was successfully rendering the Grid, but showing me the spinners again. Do I have to handle it differently when using no TSX?

**Comment by agubler** [comment]
@yduman No problem at all 😄 

It should work with `TSX` or using the `v()` and `w()` pragmas, I knocked up a quick codesandbox to demonstrate the scenario https://codesandbox.io/s/jnq8nwx2j5.

Hopefully this helps resolve your isssues.

**Comment by yduman** [comment]
Damn, it was the ternary operator that I forgot to add. Gotta keep in mind the prop diffing process... Again, thank you very much 😄
