### ISSUE TITLE
a11y Testing

### ISSUE THREAD

**Issue by kitsonk** [dojo/widgets#65]
@kitsonk commented on [Wed Nov 16 2016](https://github.com/dojo/widget-core/issues/110)

---

@agubler commented on [Fri Mar 10 2017](https://github.com/dojo/widget-core/issues/110#issuecomment-285629662)

I think that this should certainly be a concern for @dojo/widgets, perhaps be good to have some more details too.

---

@kitsonk commented on [Fri Mar 10 2017](https://github.com/dojo/widget-core/issues/110#issuecomment-285651237)

Apologies.

More details, we should leverage [`intern-a11y`](https://github.com/theintern/intern-a11y) to integrate a11y tests into for each widget and make them part of the test suite.  We should ensure that all widgets include tests the express expected results for:

- Screen Reader Expected Results
- Express expected rolls
- Are navigable via a keyboard with expected results
- Have appropriate focus during navigation

---

@agubler commented on [Fri Mar 10 2017](https://github.com/dojo/widget-core/issues/110#issuecomment-285652145)

I think we should move this to `@dojo/widgets` unless you have any objections

**Comment by kitsonk** [comment]
We should integrate `intern/a11y` and aXe into our showcase page and generate an a11y report for the showcase application.

**Comment by smhigley** [comment]
A couple quick thoughts:

- I agree with @kitsonk that aXe/any other comprehensive a11y testing tool only needs to be run on the showcase page, not on individual widgets
- We need to make sure we test the dojo theme as well as the basic widget css on the showcase page
- We should have documentation around what a11y things should be included in unit and functional tests (keyboard nav and focus, mainly)
