### ISSUE TITLE
Enable users to hook into a click of grid rows

### ISSUE THREAD

**Issue by agubler** [dojo/widgets#652]
**Enhancement**

Consider adding a hook to listen to row selection in the grid, the function should receive the item used to populate the row data.

* Possibly add a themeable `selected` class that users can customise along side the onClick handler. By default would do nothing?
* Multiple column select option? Would potentially require visual indicator that a row is selected and a mechanism to submit multiple selected rows?

**Comment by odoe** [comment]
I had added this to another issue, but this is more fitting.

We will have a need for more interactivity with the Grid. Right now it can display data just fine, but there are many cases where getting the selected row would be very helpful.

Looking at Grid, it could look something like this on the `Row` that is passed down from the `Grid`.

```
export interface RowProperties {
	id: number;
	item: { [index: string]: any };
	columnConfig: ColumnConfig[];
  updater: (rowNumber: number, columnId: string, value: any) => void;
  // optional handler
  onSelectHandler?: ({ id, [index: string]: any }) => void;
}

return v(
  'div',
  {
    // add handler
    onClick: () => {
      if (onSelectHandler) {
        onSelectHandler({ id, item });
        // probably toggle a local state property
        // for selected state too
      }
    },
    classes: [this.theme(css.root), fixedCss.rootFixed],
    role: 'row',
    'aria-rowindex': `${id + 1}`
  },
  columns
);
```

This could also open up the the opportunity to support multi-select at some point as well.

**Comment by agubler** [comment]
Resolved by https://github.com/dojo/widgets/pull/964
