### ISSUE TITLE
Select widget doesn't scroll to the initial selection

### ISSUE THREAD

**Issue by evra** [dojo/widgets#656]
**Bug**

The `Select` widget doesn't scroll to the active index selection on initial render. 

Package Version: 4.0.1

- A `select` widget has a long list of items so that the underlying `Listbox` displays a vertical scroll.
- The last item in the list is marked as active selection in the `Select` properties

**Expected behavior:**

When user opens a `Scroll` list the list is automatically scrolled to the selected item.

**Actual behavior:**

The list doesn't automatically scroll.

Please, note that this happens only for the initial render. If user scrolls down manually or uses a keyboard to select a matching item then the scroll position stays at a correct position (probably using an internal state).

**Comment by maier49** [comment]
This was addressed by #660
