### ISSUE TITLE
Select Widget automatically selects first item as 'active'

### ISSUE THREAD

**Issue by evra** [dojo/widgets#657]
**Bug**

The select widget automatically selects the first item as 'active' (focused) on **first** render. There is no programmatic way to focus on certain item (make it 'active' it terms of Listbox API)

Package Version: 4.0.0

**Expected behavior:**
Default behavior: when user opens a Select widget the first item is not focused. After user pushes the 'Down' key the first gets focused.

**Actual behavior:**
When user opens a Select widget the first item in the list is focused (active)

**Comment by maier49** [comment]
The behavior for the select widget is fairly standard. A native select element will display and focus the first option unless one is specified as being selected, and the Dojo Select widget emulates this behavior. 

A `placeholder` property can be provided to the widget if you do not want the first element rendered in the Select by default, but it will still be focused upon opening the select. If another value should be selected on first render, the widget can be passed a `value` property programatically.
