### ISSUE TITLE
Support indeterminate state in progress widget

### ISSUE THREAD

**Issue by evra** [dojo/widgets#658]
**Enhancement**

In some cases it is necessary to show indeterminate progress state. This can possibly be implemented by having an additional theme class which is applied when progress value is undefined. Concrete CSS implementations may use animations.

The aria attributes should be probably also taken into account: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_progressbar_role

**Comment by tomdye** [comment]
This work re. aria tags has been completed and we have the loading indicator widget to denote an indeterminate progress state
