### ISSUE TITLE
ListBox keyboard selection wrong behavior

### ISSUE THREAD

**Issue by CatalinNarita** [dojo/widgets#661]
**Bug**

The standalone SelectBox widget does not invalidate and re-render when a user scrolls through the list with arrow keys and then makes a selection with Enter key. 

Package Version: 4.0.1

**Code**

Sandbox: https://codesandbox.io/s/5vj6n7zw54

**Expected behavior:**

The behaviour should be the same as per selections via mouse click.

**Actual behavior:**

After Enter key is pressed, the user needs to do another action that triggers an invalidate for the new selection to be highlighted. A workaround provided by @agubler  would be to reassign the data array with its own values using the spread operator inside the onOptionSelect callback (see commented line in the sandbox).

Also thanks to tom for confirming this bug.

**Comment by tomdye** [comment]
The listbox is being replaced with a new menu widget for dojo 7 which fixes this bug. The menu widget was introduced [here](https://github.com/dojo/widgets/pull/885). You can use is as a list box.
