### ISSUE TITLE
Widgets v6 migration guide / breaking changes

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#667]
## Issue to capture breaking changes and migration guide for v5 -> v6.
Please fill in below, this will form part of a migration guide going forward.

---

#### Removed
- `invalid`
- `labelAfter`

#### Added
- `customValidator?: (value: string) => { valid?: boolean; message?: string; } | void;`
- `onValidate?: (valid: boolean | undefined, message: string) => void;`
- `leading?: () => DNode;`
- `trailing?: () => DNode;`
- `helperText?: string;`

#### PRs
- https://github.com/dojo/widgets/pull/682
- https://github.com/dojo/widgets/pull/680
- https://github.com/dojo/widgets/pull/679
- https://github.com/dojo/widgets/pull/664

---

### Enhanced Text Input
**DELETED**
#### PRs
- https://github.com/dojo/widgets/pull/680

---

#### Added
- `open` class alongside 'root' when dialog is open
- `underlayEnterAnimation`/ `underlayExitAnimation` properties
- Ability to set any of the enter / exit animations to `null` to stop any animation from running
#### PRs
- https://github.com/dojo/widgets/pull/695

---

#### Removed
- `labelAfter`
#### Added
- `helperText?: string;`
#### PRs
- https://github.com/dojo/widgets/pull/682

---

#### Removed
- default `collapseWidth` of `600`. If no `collapseWidth` is passed it will no longer collapse
#### PRs
- https://github.com/dojo/widgets/pull/666

---

#### Removed
- `labelAfter`
#### Added
- `helperText?: string`
#### PRs
- https://github.com/dojo/widgets/pull/696

---

#### Added
- `.actions` wrapper for toolbar actions which will automatically switch from row to column view when menu is collapsed into slide pane.
- `align` option to set the alignment of the embedded SlidePan that is displayed on narrow screens
#### PRs
- https://github.com/dojo/widgets/pull/699
- https://github.com/dojo/widgets/pull/681

**Comment by schontz** [comment]
Should `SplitPane.collapsWidth` be renamed to `collapseSize` since `SplitPane`s are both rows or columns?

**Comment by agubler** [comment]
@tomdye can this be closed?
