### ISSUE TITLE
Stop the background scrolling while the dialog is opened

### ISSUE THREAD

**Issue by falcusanradu** [dojo/widgets#669]
**Bug** 

I can't stop the background scrolling if  I'm using the dojo Dialog. I tried to use event.stopPropagation(), but the propagation didn't stopped. I found a workaround, but unfortunatly it's not the best solotuin because I'm modifying the global css. Is there any better solution to stop the background scrolling? 

Package Version: "@dojo/widgets": "5.0.0"

**Code**
Is there any way to stop the propagation without modifying the global css? (document.body.classList)
https://codesandbox.io/s/l4nmr06y0m

**Expected behavior:**
I shouldn't be able to scroll in the background (without modifying the global css)

**Actual behavior:**

I'm able to scroll in the background while the dialog is opened

**Comment by aciccarello** [comment]
I took a quick look at the codesandbox example but it doesn't seem to be styled at all. I wonder if that is because of a change to codesandbox.

**Comment by DanGandila** [comment]
Hi all,
anything new here? This bug is of concern for me and my team as well. Will this be fixed with dojo v.6?

**Comment by tomdye** [comment]
@DanGandila this has been fixed for the upcoming v7 release but I am not sure a backport will be possible as the dialog has since been converted from a class to a function based widget which also utilises a bodyscroll middleware.
