### ISSUE TITLE
Toolbar: Should apply flex layout to menu items

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#670]
**Enhancement** 

It is currently down to the widget user to implement a layout for their links when using the toolbar. This means that they must manually add classes etc to layout their links differently between the header and the slide pane.

We should change the toolbar to automatically layout the toolbar children using `flex-direction: row` for the toolbar and `flex-direction: column` for the slide pane.

**Comment by msssk** [comment]
> `flex-direction: column` for the slide pane.

This seems like something we want to do specifically for Toolbar, correct? As in, this style only applies for a slide pane that is in a Toolbar, and not a style we want to apply to the slide pane widget source.

How do I modify the theme within Toolbar that is passed to SlidePane to achieve this?
