### ISSUE TITLE
Toolbar: Slide pane position

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#671]
**Enhancement** 

The toolbar should provide a property to toggle if the collapsed slide pane is on the left or the right of the page.

**Comment by msssk** [comment]
Do we want to restrict to left or right alignment, or do we want to allow any of the [`Align.*` options in slide-pane](https://github.com/dojo/widgets/blob/76d807228de66290b5b574530596c0bae8917b39/src/slide-pane/index.ts#L19-L24)?
