### ISSUE TITLE
Select: onChange event differences

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#675]
**Enhancement** 

The native / non-native elements currently have different `onChange` events. The native version requires a `getOptionValue` property to be implemented whereas the non-native does not.
We should normalise these two onChange events and the API in general for Select.

Update [by @sammenza]: Specifically Select widget should have the following changed:
- Update `options` property to be of type `{value: string, label?: string}[]`
- Allow select to accept `<option>` child nodes
- Remove `getOptionValue` property from Select widget

**Comment by tomdye** [comment]
This is part of a larger piece of work to align select / combo box apis and to update callbacks to use `onValue`

**Comment by sammenza** [comment]
There are a bunch of elements that have the property `onChange` are you referring to an update for select and the combobox specifically?

**Comment by sammenza** [comment]
To clarify when you say native are you referring to dojo's Select widget?

**Comment by sammenza** [comment]
Why is there a native and non native version in the first place?

**Comment by sammenza** [comment]
These changes would also invalidate `getOptionLabel` btw

**Comment by sammenza** [comment]
If this is the case would we want to keep the `getOptionLabel` property?

**Comment by tomdye** [comment]
This has been fixed via https://github.com/dojo/widgets/pull/962
