### ISSUE TITLE
Extending SplitPane: size trailing pane

### ISSUE THREAD

**Issue by schontz** [dojo/widgets#698]
**Enhancement** 

Extend SplitPane so that the size can apply to the trailing pane instead of the leading one. A sample use case: your site has navigation in the trailing (right) pane and you want the leading (left) pane to fill up the rest of the screen. The current implementation always "freezes" the left pane at `size` and the right pane takes up the rest of the screen.

**Comment by schontz** [comment]
I should restate the problem: I want to have a `SplitPane` where size applies to the second pane instead of the first. If this is worth being a general-purpose use case, I could try and make a PR for it. A couple ways to go at it:

`sizeAppliesTo?: 0 | 1`

or

`sizeAppliesToSecond?: boolean`

**Comment by tomdye** [comment]
Closing as we're removing splitpane in favour of fixed column layouts
