### ISSUE TITLE
README/package suggestions

### ISSUE THREAD

**Issue by schontz** [dojo/widgets#700]
A couple suggestions:

1. Use `npx tsc -w` instead of `tsc -w`, in case the global `tsc` is running a different version. Or solve the issue by adding it to run `scripts`, e.g. `npm run watch`.

2. Consider adding `grunt dev`, `grunt dist`, and `grunt test` commands to `package.json` `scripts` to aid in discoverability.

I considered making a PR, but I assume the project leads would want to consider what to add and how to name, so I defer.

**Comment by agubler** [comment]
@schontz Hey! For v6, we'll are going to move over to use `dojo/cli-build-widget`, so we'll be replacing all the existing scripts with dojo ones provided by the cli command.

**Comment by schontz** [comment]
Perfect.
