### ISSUE TITLE
Increase Page Size 

### ISSUE THREAD

**Issue by ILoveITScience** [dojo/widgets#703]
It seems like toe page Size is hard coded to 100
![image](https://user-images.githubusercontent.com/17782816/55554026-12d41f80-56e2-11e9-8657-47f736d9ce96.png)

Or here: line 63
https://github.com/dojo/widgets/blob/master/src/grid/widgets/Grid.ts

We would like to increase the size

**Comment by agubler** [comment]
@iloveitscience why do you want to increase the page size value?

**Comment by ILoveITScience** [comment]
It's a workaround for a missing feature (server side filtering on the backend).

**Comment by agubler** [comment]
@Iloveitscience how do you mean a missing feature? Missing from the grid?

Can you give an example of your use case?

**Comment by ILoveITScience** [comment]
Well, at the moment the backend does not support server side filtering. If we could increase the page size to 1000 we would have all the data on the client and could do client side filtering.

**Comment by agubler** [comment]
@ilovescienceit you can do that without increasing that variable, I’ll dig out an example for you.

**Comment by agubler** [comment]
@ILoveITScience Here is an example of creating a custom rest fetcher, that fetches the whole dataset then operates on the data on the client side for filtering and sorting - https://github.com/dojo/widgets/issues/643#issuecomment-454756476

**Comment by agubler** [comment]
I think that the proposed solution has worked for the use case.
