### ISSUE TITLE
Validate instructions for running widget examples

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#718]
We should validate that the existing instructions for running widget examples are correct.
I believe the correct way to run these is via a http-server running from the project root. The npm module `http-server` is perfect for such a task.

**Comment by agubler** [comment]
@tomdye There have been some recent issues with `http-server` due to one it's dependencies (`ecstatic`) having versions with a security vulnerability being removed from npm.

Perhaps https://www.npmjs.com/package/serve is a better alternative

**Comment by tomdye** [comment]
Thanks for adding this @agubler , wasn't aware and wholly agree.
