### ISSUE TITLE
LabeledProperties#label should allow DNode

### ISSUE THREAD

**Issue by bitranch** [dojo/widgets#728]
**Enhancement**

Currently the `LabeledProperties` interface only allows a string for the `label` property. The underlying `Label` widget, however, accepts a `DNode`. The `label` property should allow passing a `DNode` rather than only a string.

Note that the current `string` limitation requires refactoring code to use an explicit `Label` widget whenever any kind of formatting is needed.

Package Version: `@dojo/widgets` (all versions)

**Code**

**Expected behavior:**

**Actual behavior:**

**Comment by tomdye** [comment]
We need to discuss the approach for this and see how it fits in with our functional children approach for dojo 7. We are moving away from render properties and properties that accept DNodes.

**Comment by tomdye** [comment]
This has been addressed via changes to our labels to be child renderers of type `RenderResult`
