### ISSUE TITLE
TextInput type 'number' missing configuration

### ISSUE THREAD

**Issue by thomasxb** [dojo/widgets#735]
**Bug** 

Package Version: 

**Code**

w(TextInput, {	key: 'priceInput', type: 'number', min: 0, max: 999, step: 0.1,
 						required: true});

**Expected behavior:**

min, max and step properties to be supported

**Actual behavior:**

min, max and step properties not supported, making numeric input fields with auto-validation completely unusable (no none-integers possible)

**Comment by tomdye** [comment]
Good catch, I noticed this too but did not yet get around to fixing it. Would you like to contribute by raising a pull request to add these in? Happy to provide any guidance necessary.

**Comment by thomasxb** [comment]
Why not. Just give me a pointer on where to start. Never contributed using github before (I remember my last contribution a few years ago sending to RMS via e-mail :-) )

**Comment by tomdye** [comment]
Nice one, we have a contributing guide here: https://github.com/dojo/meta/blob/master/CONTRIBUTING.md.
Essentially fork the repo, create a feature branch and raise a PR back to master from there.
The change itself is pretty simple. Just need to add the properties in question and pass them to the `input` within the render function.

**Comment by agubler** [comment]
This is now supported with the number input (#841 )
