### ISSUE TITLE
Icon widget - add Material support

### ISSUE THREAD

**Issue by msssk** [dojo/widgets#738]
- [Material Design Icons](http://google.github.io/material-design-icons/)
- [Material Icon Library](https://material.io/tools/icons/)

## Overview

This issue is concerned with implementing a Material themed icon component.
[Material Components](https://github.com/material-components/material-components-web) does not have an icon component, but provides an icon library linked above. Recommended usage is with the icon font. 

## Changes to structure

Material icons examples use a simple DOM structure: `<i>icon_name</i>` and no pseudo-class. Dojo's icon component using FontAwesome icons adds the icon visually with `.iconClass:before`. The Material approach is friendlier to screen readers.

## Tasks

- [ ] Restructure and update props
- [ ] Implement Material theme
- [ ] Add validation

**Comment by msssk** [comment]
Material Components has distinct components for [button](https://github.com/material-components/material-components-web/tree/master/packages/mdc-button) and [icon-button](https://github.com/material-components/material-components-web/tree/master/packages/mdc-icon-button). `icon-button` is a button with an icon, so it is not equivalent to Dojo's `icon` component.

**Comment by msssk** [comment]
Do we have any plans to change the structure of icon widget? Or could we do so conditionally, depending on if the Material theme is loaded? The Material icons work with DOM like: `<i class="icon">icon_name</i>`, but our structure is currently `<i class="icon icon_name"></i>`

**Comment by tomdye** [comment]
This has been completed
