### ISSUE TITLE
Switch test from using `sleep` to `find` 

### ISSUE THREAD

**Issue by samenz** [dojo/widgets#749]
**Enhancement** 
Currently we use `sleep` in our functional tests for widgets. However `sleep` makes the runner wait a fixed time and if the element isn't there in time the test fails. This creates brittle tests and is also bad for pipeline run time.

A more efficient way would be to use leadfoot's `find` or `executeAsync` which will keep polling for the client side data until the the element is found or it reaches the timeout set by `setExecuteAsyncTimeout`.

**Comment by tomdye** [comment]
closing as we no longer have our functional tests
