### ISSUE TITLE
Use `root` classname consistently for outermost HTMLElement of widgets

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#75]
@tomdye commented on [Tue Mar 14 2017](https://github.com/dojo/widget-core/issues/407)

**Enhancement** 

Do we feel that it would be advantageous to consistently use `root` as the outermost classname for all of our dojo 2 widgets?

- Would provide a consistent way to pass `overrideClasses` to widget outer HTMLElement.
- Would lower the barrier to entry to applying classes to 'black box' widgets.
- Allows the widget author to determine the `root` element in the case of widgets such as `Dialog`
- Allows `spacing` type rules to be applied safely to a widget with greater ease.

**Example**

``` css
/* myLayout.css */
.marginClass {
   margin: 10px;
}
```

``` typescript
import * as myLayout from './myLayout.css';

/* can safely target the root class */
w(Button, { overrideClasses: { root: myLayout.marginClass } });
```

---

@tomdye commented on [Tue Mar 14 2017](https://github.com/dojo/widget-core/issues/407#issuecomment-286503637)

@rishson  Do we feel this is `beta1` or `beta2`? I suspect the latter.

---

@matt-gadd commented on [Fri Mar 17 2017](https://github.com/dojo/widget-core/issues/407#issuecomment-287382044)

@tomdye this is in the wrong repo no?

---

@tomdye commented on [Fri Mar 17 2017](https://github.com/dojo/widget-core/issues/407#issuecomment-287382161)

correct, can it be moved to `widgets` or do i have to create a new one?

**Comment by rishson** [comment]
If we are going to do this, then we need to check the following are compliant:

- [ ] Button
- [ ] CheckBox
- [ ] ComboBox
- [ ] Dialog
- [ ] Label
- [ ] Menu
- [ ] NavBar
- [ ] Radio
- [ ] SlidePane
- [ ] Slider
- [ ] TabPane
- [ ] TextArea
- [ ] TextInput
- [ ] TimePicker

**Comment by tomdye** [comment]
Dialog was missing `root` class. Label can have `root` class added once it's `classes` property is removed in another PR.
