### ISSUE TITLE
TextInput autocomplete and events

### ISSUE THREAD

**Issue by sebilasse** [dojo/widgets#752]
**Bug**

While I am working on [my material theme](https://github.com/dojo/widgets/issues/615#issuecomment-488740214) comboBox I was unable to get the `autocomplete` value in the onInput event crossbrowser.
The underlying problem is described here https://stackoverflow.com/questions/8548533/any-event-triggered-on-autocomplete

And an enhancement would be to allow `autocomplete` to be any of these values:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

Package Version: current

**Expected behavior:**

Having a crossbrowser event for the autocomplete triggered by the browser.

**Actual behavior:**

It is not triggered in various browsers.

**Comment by tomdye** [comment]
Autocomplete is currently set to `boolean | string` for text input and thus should support all of the listed values
