### ISSUE TITLE
Several widgets have out-of-date README examples

### ISSUE THREAD

**Issue by bitranch** [dojo/widgets#755]
**Bug**

*Doc*: The example(s) in the README for several widgets reference a `describedBy` property that no longer exists on the widget. (Widgets with this issue are at a minimum `radio`, `checkbox`, and `button`. I haven't done a full audit of all the widgets, looking for this issue.)

Attempting to use the examples for these widgets results in a TypeScript error.

Based on history, `describedBy` was moved to the `aria` interface about a year and a half ago (Jan 2018). Looking at the tests, the property should be `aria: { describedBy: 'foo' }` instead of `describedBy: 'foo'`.

Package Version: `@dojo/widgets ~4 to current`.

**Comment by devpaul** [comment]
Resolved as part of #917
