### ISSUE TITLE
Create a static widget type - HTMLWidget / StaticWidget for plain html elements

### ISSUE THREAD

**Issue by Tomdye** [dojo/widgets#76]
# Enhancement

Proposal is that we should create a plain widget (basically re-purpose `createWidget` or similar) such that we can use it within apps to create HTML elements.
It should be created such that we can have `HTML Container` and `HTML TextNode` elements with typed `tagname`.
- createStaticContainer
- createStaticTextNode
## Reasoning

My reasoning is that when working on the monster app with Dojo 2 I feel that the code would be clearer if when creating `html` structures (rather than traditional widgets), they were named as such.

**Comment by matt-gadd** [comment]
This is no longer relevant.
