### ISSUE TITLE
Should we use the `file.m.css` naming convention for css-module files

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#76]
**Enhancement** 

When working with Dojo 2 I have found that there are occasions where we do not want to run some css files through our css-module process.
Examples include the `widgets.css` file containing all styles for `amd` loaders and I have found, the `theme.css` file we need to generate per theme for the same reason.

We currently have exception rules for `widget.css` and `variables.css` in our grunt build pipeline but no such approach for our `webpack-build`.

**Comment by tomdye** [comment]
Have added `beta-blocker` for now, happy for it to be removed it we don't feel it's appropriate

**Comment by tomdye** [comment]
@bitpshr @smhigley @mwistrand i'd appreciate your thoughts

**Comment by smhigley** [comment]
We should probably keep in mind that we've already discussed breaking `variables.css` into separate variable files, so whatever solution we use should ideally be flexible enough to handle multiple changing file exceptions.

**Comment by bitpshr** [comment]
I think using `.m.css` or `.module.css` is a good idea. Our setup is brittle right now, this would definitely help.

**Comment by agubler** [comment]
Is this a beta blocker @rishson @matt-gadd, if so we probably need someone to pick this up before Friday.

**Comment by tomdye** [comment]
I'd rather we went for `m.css` over `module.css` personally. I think it's a worthwhile exercise to make the change
