### ISSUE TITLE
Use codesandbox example approach for widget examples

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#782]
**issue writing in progress**

We have a common pattern for creating dojo examples in codesandbox using [dojo-example-runner](https://www.npmjs.com/package/dojo-example-runner). 

We should adopt this for our widget examples. This is capable of being built using the cli and themed via a built theme package as well as being ran on code sandbox.

**Comment by agubler** [comment]
The example app supports running in code sandbox (once an alpha of widgets is released)
