### ISSUE TITLE
Typeahead Widget - using resources / data middleware

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#795]
This widget should use a `text-input` and a `menu` to facilitate a typeahead.
This will differ from the combo / filtering select as it will not be provided with a full list of results to filter.

The typeahead should provide a callback when the search string has changed and accept an array of results to show in the menu / listbox. This will enable back end searches and other complex async functions to run. 

A custom row renderer can be used if the data returned does not match the default object or has specific display requirements.

**Comment by samenz** [comment]
How many results would be displayed?

**Comment by tomdye** [comment]
I'm currently working on this as part of the menu / data-middleware work @samenz. Results to display will be determined by the menu properties and the resource that the typeahead is using.
