### ISSUE TITLE
Non-native Select inside of Title-Pane does not render the Listbox correctly

### ISSUE THREAD

**Issue by nikkabi** [dojo/widgets#804]
**Bug** 

Package Version: 6.0.0

**Code**

There is a Repository here:
https://github.com/nka089/select-accordion

**Expected behavior:**

behavior like native element.

**Actual behavior:**

The native goes out of the accordion. The non-native remains in the pane, but can not scroll.

**Comment by tomdye** [comment]
I believe this will be fixed by the new `Select` implementation we are working on for dojo 7 release

**Comment by nikkabi** [comment]
@tomdye If so, it can be closed.
