### ISSUE TITLE
Switch widget

### ISSUE THREAD

**Issue by rishson** [dojo/widgets#81]
This widget should offer toggle switch behaviour, 

**Specification**

<img width="81" alt="screen shot 2017-03-21 at 4 34 51 pm" src="https://cloud.githubusercontent.com/assets/468596/24158503/6f37d308-0e54-11e7-9589-d880f03caa9a.png">

Features
- The widget can be enabled/disabled
- The widget can have leading/trailing labels
- The widget labels can contain icons
- The widget labels can contain unicode text
- Clicking on a leading label will put the switch in the 'off' position (if it was in the 'on' position) 
- Clicking on a trailing label will put the switch in the 'on' position (if it was in the 'off' position) 
- Clicking on the switch itself, will toggle the switch between the 'on' and 'off' position.

Value-add of the widget (e.g. why use rather than just use VDom directly)
builds on the existing `checkBox` and offers a mobile visual look/feel and ux.

List of callback funcs that can be passed in props (if any)
as for `checkBox`

Mouse/keyboard interactions (if any)
possibility to show different tooltips when hovering over leading and trailing labels

Mandatory/valid/empty/wait states (if any)
none

Is the widget controlled/uncontrolled
as per `checkBox`

List of any icons needed
any icon in font-awesome that we ship should be usable as either a leading or trailing label.

Design input required

Any other considerations:

**Questions**

**Acceptance criteria**
When I specify an label with text and an invalid icon, then I expect the text to be rendered without the icon.
When I specify a label with unicode text, then I expect it to render correctly (including adjusting for height of non-latin chars).

**Commentary**
@smhigley suggested we incorporate this into the `checkbox` widget. Would it be preferable to extend that widget, so that you could change the styling by passing in a prop, e.g. `{switch: true}`?
 
Would the above approach have any appreciable effect on the size of our widgets, in that you you get 2-for-1 with a switch-checkbox?

If this is to be a standalone widget (e.g. not an extension of `checkbox`) then I'll add a full specification to this issue.

**Comment by tomdye** [comment]
@rishson it's likely just an extension / mode on a checkbox

**Comment by bitpshr** [comment]
I'm going to try out extension vs. adding internal CheckBox logic.

**Comment by smhigley** [comment]
If we don't need the words "off" and "on", it could just add a class name and do it all with css. If we want words, then we need i18n or extra properties to pass them in.

**Comment by rishson** [comment]
@bitpshr @tomdye @smhigley spec updated with more betterness.
