### ISSUE TITLE
Landing page for widget documentation app

### ISSUE THREAD

**Issue by agubler** [dojo/widgets#813]
**Enhancement**

At the moment the landing page for the documentation application is a blank page, it would be better if there was a general way to navigate to the docs from the home page.

Also a link in the menu to go back to the home page.

**Comment by JamesLMilner** [comment]
This is my thoughts for general layout of the landing page:

![Screenshot_20191115_123952](https://user-images.githubusercontent.com/8822075/68944270-5e38cb00-07a5-11ea-9e13-05457e6456ff.png)
