### ISSUE TITLE
Example: checkbox

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#819]
Split appropriate existing examples into separate files using functional approach and icache and move into the correct `/src/examples/widgets` subdirectory.

**Comment by JamesLMilner** [comment]
Can this be closed now? It looks like they're in @rorticus @tomdye 
![Screenshot_20200110_172102](https://user-images.githubusercontent.com/8822075/72172647-94718000-33cd-11ea-9f66-8d92cc74c4b4.png)
