### ISSUE TITLE
Base properties for text input derivatives 

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#844]
When starting to create `Email` / `Number` input etc we have been discussing which of the `TextInput` properties should be implemented by all. 
Without the existence of a set of base properties we will likely run into inconsistencies between implementations.

The base TextInput will implement all base properties plus the full set of properties an `input` can take. Each of the specific inputs will implement the base properties plus any other properties that are relevant to it.

**Comment by tomdye** [comment]
For example:

```ts
interface NumberInputProperties extends BaseInputProperties {
   min?: number;
   max?: number;
   step?: number;
}
```

**Comment by samenz** [comment]
Hmm what should be included in `BaseInputProperties`? Taking a stab, here's a rough draft.
```
	aria?: { [key: string]: string | null };
	autocomplete?: boolean | string;
	disabled?: boolean;
	label?: string;
	name?: string;
	onBlur?(): void;
	onFocus?(): void;
	onValidate?: (valid: boolean | undefined, message: string) => void;
	onValue?(value?: string): void;
	onClick?(): void;
	onOver?(): void;
	onOut?(): void;
	placeholder?: string;
	readOnly?: boolean;
	required?: boolean;
	valid?: { valid?: boolean; message?: string } | boolean;
	value?: string;
	widgetId?: string;
```

**Comment by tomdye** [comment]
@samenz take a look at the PR I raised #843

**Comment by tomdye** [comment]
I believe base properties to be:

- aria
- autocomplete
- disabled
- helperText
- label
- labelHidden
- leading
- name
- onBlur
- onClick
- onFocus
- onKeyDown
- onKeyUp
- onOut
- onOver
- onValidate
- onValue
- placeholder
- readOnly
- required
- trailing
- value
- widgetId

**Comment by tomdye** [comment]
closing this now as has been implemented
