### ISSUE TITLE
Configurable BASE_YEAR in calendar/date-picker

### ISSUE THREAD

**Issue by krezovic** [dojo/widgets#858]
**Enhancement**

Package Version: master

In DatePicker.ts, there's BASE_YEAR hardcoded to 2000. This makes the DatePicker always start at 2000, even if next year is 2020 (the last year by default in that list). It would be nice so we can configure that, so we don't go that back in the past.

Additionally, there's a year range in DatePicker.ts, but never used in Calendar, so that's also not a solution.

**Comment by devpaul** [comment]
Hi @krezovic,

The `BASE_YEAR` in `DatePicker` is used as an anchor for determining the offset of the years displayed on the year select drop-down. The year drop down in the `Calendar` will always start by showing the page of years with the currently selected year. So for 2020 the year select will contain that year.

![image](https://user-images.githubusercontent.com/331431/70166089-4f955380-1681-11ea-9f49-d996669d2d78.png)

`Calendar` will always show a page of years starting on a multiple of 20 for consistency sake. We took a look at changing this, but ultimately we decided against adding too many properties to `Calendar` and `DatePicker` to maintain a straight-forward user experience.
