### ISSUE TITLE
Material theme for text input

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#953]
material Text input details can be found here: https://material.io/develop/web/components/input-controls/text-field/.
We need to consider reuse for textarea when doing this work.
Our existing dom structure should support the general styles along with leading / trailing sections. We may be unable to support the floating labels and thus may need to style them with appropriate material typography - this has been covered in the label issue.

**Comment by nicknisi** [comment]
@tomdye What is our plan here for labels? Do we want to support the material floating label, or have it look different?
