### ISSUE TITLE
`on<Action>` vs. `onRequest<Action>`

### ISSUE THREAD

**Issue by bitpshr** [dojo/widgets#96]
**Enhancement**

Components should consistently use `on<Action>` style property names instead of `onRequest<Action>` style property names. Even though the latter is technically more accurate, it's  also more verbose and can be slightly confusing.

Package Version: latest

**Comment by rishson** [comment]
My opinion: I think internal handled things can be `onslideleft` etc, as this is what is happening.
I prefer `onRequestClose` if the widget is controlled, as that is what is occurring; the widget is requesting a `close` but it is up to whatever is controlling the widget, to actually respond to and complete the request.
The widget should encapsulate the actions that could lead to a `close`, e.g. `closeClicked` `swippedJustEnough`, the 'API' for the widget is `onRequestClose` as it's going external to the widget.

**Comment by mwistrand** [comment]
I agree with @rishson. A property name like `onClose` suggests that the widget either has just been closed or is about to close. If, however, the action implied in the name will not actually take place without further action from the handler, then the name `onRequest<Action>` is less confusing/misleading.

**Comment by bitpshr** [comment]
Agreed. I think we can close this and the associated PR for now.
