### ISSUE TITLE
NativeSelect Component

### ISSUE THREAD

**Issue by samenz** [dojo/widgets#973]
**Enhancement**

We need a native select widget that will use the browser's native html select element to accommodate applications that cannot use the dojo widget's select built with custom components.

**Asks**
- Create a separate NativeSelect widget instead of adding a useNative property. This will remove complexity from the select widget's api.

**Comment by tomdye** [comment]
I believe the use case for this is likely for mobile applications where the developers want to make use of native controls etc.
