### ISSUE TITLE
Improve Card implementation

### ISSUE THREAD

**Issue by tomdye** [dojo/widgets#978]
## Enhancement 

Current card implementation requires the user to use the card css classes from the default theme to apply styling / positioning to a card's child nodes. 
This is not an ideal solution as it does not match patterns used elsewhere in the dojo widgets nor does it allow theming to work appropriately.

We should come up with a better way to do this.
Possible solutions are as follows:

### render props / child render props

This would provide the users with props they can pass to render their content in the correct position.
ie.
```tsx
<Card primaryContent={renderPrimary} secondaryContent={renderSecondary} />
```
The down side of this is that is gives the user no control over where they place each of these render results. 

### Child widgets

This would provide the users with an assortment of smaller widgets they can use to render styled content. ie.
```tsx
<Card>
   <CardPrimary>primary stuff</CardPrimary>
   <CardButtons>{...buttons}</CardButtons>
</Card>
```
This would give users greater flexibility over where they place their children but removes the ability for our card widget to be opinionated about its children's layout / positioning which may be important for some layouts.

### Card derivatives with render / child render props

This, I feel, gives us the best all-around flexibility and control as we can specify different card types, ie. `MediaCard` / `PrimaryCard` / `SubtitleCard` and with such cards, provide the users with a specific, typed childen render object which they can use.
This maintains the ability to be opinionated about layout and removes the need to use theme classes from card. It also encourages users to create their own card templates etc which they would use within their own apps.

```tsx
<MediaCard imgSrc="imgSrc">
{{ 
   title: () => "I am the title",
   buttons: () => <RaisedButton>hello</RaisedButton>
 }}
</MediaCard>
```

```tsx
<SubtitleCard>
{{
   title: () => "card title",
   subtitle: () => "card sub title"
}}}
</SubtitleCard>
```

**Comment by tomdye** [comment]
I believe that #3 (card derivatives) is the approach that we should take.

**Comment by nicknisi** [comment]
Looking at the examples we have now, it seems like the named children would probably need to consist of the following:

```tsx
<Card>
	{{
		title: () => "card title",
		subtitle: () => "card sub title",
		body: () => "card body",
		media: () => <img src="foo.png"/>,
		actions: () => (
			<Button onClick={() => {}}>Click me</Button>
		)
	}}
</Card>
```

`media` would need to be a child rather than a prop to work with our example of using a div with a CSS gradient on it. As for props that would exist on the card, the only one I can currently see based on our examples is a `square?: boolean` prop. that would add the `mediaSquared` class for use with media.

**Comment by tomdye** [comment]
i think we would want `primary` / `secondary` / `actionButtons` / `actionIcons` and not body. title / subtitle could likely just be props as they're just a string. We basically dont want users to need to use the `card.m.css` file themselves anymore.
